### ISSUE TITLE
INSUFFICIENT_FUNDS after /forcesell all

### ISSUE THREAD

**Issue by botum** [gcarq/freqtrade#102]
Disclose: bot was stoped but killed afterward, after selling all. Sell was completed.

`Traceback (most recent call last):
  File "./freqtrade/main.py", line 91, in _process
    state_changed = handle_trade(trade) or state_changed
  File "./freqtrade/main.py", line 183, in handle_trade
    execute_sell(trade, current_rate)
  File "./freqtrade/main.py", line 137, in execute_sell
    order_id = exchange.sell(str(trade.pair), limit, trade.amount)
  File "/var/local/user/freqtrade/freqtrade/exchange/__init__.py", line 110, in sell
    return _API.sell(pair, rate, amount)
  File "/var/local/user/freqtrade/freqtrade/exchange/bittrex.py", line 62, in sell
    amount=amount))
RuntimeError: INSUFFICIENT_FUNDS params=(BTC_DASH, 0.0626001, 0.09763458)`

**Comment by alxnegrila** [comment]
This happens even when you have no funds to fill a buy signal. It would be nice to be aware of the balance of stake_currency and stop creating new trades if it's lower than stake_amount

Traceback (most recent call last):
  File "./freqtrade/main.py", line 70, in _process
    trade = create_trade(float(_CONF['stake_amount']))
  File "./freqtrade/main.py", line 234, in create_trade
    order_id = exchange.buy(pair, buy_limit, amount)
  File "/vagrant/freqtrade/freqtrade/exchange/__init__.py", line 92, in buy
    return _API.buy(pair, rate, amount)
  File "/vagrant/freqtrade/freqtrade/exchange/bittrex.py", line 52, in buy
    amount=amount))
RuntimeError: INSUFFICIENT_FUNDS params=(BTC_QTUM, 0.0016725, 0.5964125560538117)

**Comment by pramss** [comment]
is there any way to fix it? since after this error occurs, the bot will force close again. 
and when the bot starts again, it will immediately be killed again with the same error but different amount.

`Status: Got RuntimeError:
Traceback (most recent call last):
  File "./freqtrade/main.py", line 91, in _process
    state_changed = handle_trade(trade) or state_changed
  File "./freqtrade/main.py", line 162, in handle_trade
    execute_sell(trade, current_rate)
  File "./freqtrade/main.py", line 118, in execute_sell
    order_id = exchange.sell(str(trade.pair), limit, trade.amount)
  File "/home/development/freqtrade-master/freqtrade/exchange/__init__.py", line 118, in sell
    return _API.sell(pair, rate, amount)
  File "/home/development/freqtrade-master/freqtrade/exchange/bittrex.py", line 63, in sell
    amount=amount))
RuntimeError: INSUFFICIENT_FUNDS params=(BTC_TIME, 0.00290784, 0.35031466)`

**Comment by seansan** [comment]
Having this error again. Dont know how I solved it last time. Delete DB? Would be good if the buy command first checks if we still have the funds

**Comment by seansan** [comment]
Maybe bot can check av balance first? (and exclude reserved funds already in buy/trade)
