### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by phacts** [gcarq/freqtrade#103]
This all just occurred on the latest version of the `develop` branch, which I pulled within the last two hours.

I've been running the bot with `"dry_run": true` to check if it's stable, and I've hit an error that kills the loop altogether, crashing the python script.

Just FYI - I don't have any BTC balance in my bittrex account at the moment, so I'm not sure if that's causing the problem, though I assume not, since it's a dry run.  Also, here are the pairs I'm whitelisting:

```
"pair_whitelist": [
            "BTC_VTC",
            "BTC_LTC",
            "BTC_OK",
            "BTC_WAVES",
            "BTC_XRP",
            "BTC_SALT",
            "BTC_RLC",
            "BTC_ETH",
            "BTC_BCC",
            "BTC_PIVX",
            "BTC_STRAT",
            "BTC_XZC",
            "BTC_LUN"
        ]
```

And here's the error I'm seeing:

```
2017-11-15 00:48:38,788 - freqtrade - INFO - Checked all whitelisted currencies. Found no suitable entry positions for buying. Will keep looking ...
2017-11-15 00:48:48,267 - freqtrade - INFO - Checking buy signals to create a new trade with stake_amount: 0.050000 ...
Traceback (most recent call last):
  File "./freqtrade/main.py", line 361, in <module>
    main()
  File "./freqtrade/main.py", line 355, in main
    dynamic_whitelist=args.dynamic_whitelist,
  File "/Users/sgrimm/dev/cryptos/bots/freqtrade/freqtrade/misc.py", line 52, in throttle
    result = func(*args, **kwargs)
  File "./freqtrade/main.py", line 70, in _process
    trade = create_trade(float(_CONF['stake_amount']))
  File "./freqtrade/main.py", line 223, in create_trade
    if get_buy_signal(_pair):
  File "/Users/sgrimm/dev/cryptos/bots/freqtrade/freqtrade/analyze.py", line 99, in get_buy_signal
    dataframe = analyze_ticker(pair)
  File "/Users/sgrimm/dev/cryptos/bots/freqtrade/freqtrade/analyze.py", line 82, in analyze_ticker
    ticker_hist = get_ticker_history(pair)
  File "/Users/sgrimm/dev/cryptos/bots/freqtrade/.env/lib/python3.6/site-packages/cachetools/__init__.py", line 46, in wrapper
    v = func(*args, **kwargs)
  File "/Users/sgrimm/dev/cryptos/bots/freqtrade/freqtrade/exchange/__init__.py", line 133, in get_ticker_history
    return _API.get_ticker_history(pair, tick_interval)
  File "/Users/sgrimm/dev/cryptos/bots/freqtrade/freqtrade/exchange/bittrex.py", line 106, in get_ticker_history
    for tick in data['result']:
TypeError: 'NoneType' object is not iterable
```

**Comment by phacts** [comment]
Also, I've got all of the updated dependencies installed, so it's not anything like that.  It looks like the sanity check is assuming `data['result']` is iterable, and it's coming back as a `NoneType`.

From `bittrex.py`:

```
        data = _API_V2.get_candles(pair.replace('_', '-'), interval)
        # This sanity check is necessary because bittrex returns nonsense sometimes
        for prop in ['C', 'V', 'O', 'H', 'L', 'T']:
            for tick in data['result']:
                if prop not in tick.keys():
                    logger.warning('Required property %s not present in response', prop)
                    return []
```

**Comment by phacts** [comment]
I bet it hit an API limit and there's just no data.

**Comment by gcarq** [comment]
Thanks for the comprehensive bug report, I'll take a look

**Comment by ahonnecke** [comment]
I think that I might be seeing this again:

## Step 1: Have you search for this issue before posting it?

If you have discovered a bug in the bot, please [search our issue tracker](https://github.com/freqtrade/freqtrade/issues?q=is%3Aissue). 
If it hasn't been reported, please create a new issue.

## Step 2: Describe your environment

  * Operating system: Centos
  * Python Version: 3.6.8
  * CCXT version: 
(.env) ubuntu@ip-172-31-47-109:~/freqtrade$ pip freeze | grep ccxt
ccxt==1.18.992
  * Branch: Master
  * Last Commit ID:
(.env) ubuntu@ip-172-31-47-109:~/freqtrade$ git log --format="%H" -n 1
0d9d23a888d1189a6c9b6e6d453d0aee08183724

  
## Step 3: Describe the problem:

Runs for some time, then throws this
`
2019-09-04 18:39:37,168 - freqtrade - ERROR - Fatal exception!                                                                                                                                                     │······································································
Traceback (most recent call last):                                                                                                                                                                                 │······································································
  File "/home/ubuntu/freqtrade/freqtrade/main.py", line 49, in main                                                                                                                                                │······································································
    worker.run()                                                                                                                                                                                                   │······································································
  File "/home/ubuntu/freqtrade/freqtrade/worker.py", line 72, in run                                                                                                                                               │······································································
    state = self._worker(old_state=state)                                                                                                                                                                          │······································································
  File "/home/ubuntu/freqtrade/freqtrade/worker.py", line 110, in _worker                                                                                                                                          │······································································
    self._throttle(func=self._process, min_secs=throttle_secs)                                                                                                                                                     │······································································
  File "/home/ubuntu/freqtrade/freqtrade/worker.py", line 123, in _throttle                                                                                                                                        │······································································
    result = func(*args, **kwargs)                                                                                                                                                                                 │······································································
  File "/home/ubuntu/freqtrade/freqtrade/worker.py", line 134, in _process                                                                                                                                         │······································································
    state_changed = self.freqtrade.process()                                                                                                                                                                       │······································································
  File "/home/ubuntu/freqtrade/freqtrade/freqtradebot.py", line 135, in process                                                                                                                                    │······································································
    state_changed |= self.process_maybe_execute_sell(trade)                                                                                                                                                        │······································································
  File "/home/ubuntu/freqtrade/freqtrade/freqtradebot.py", line 458, in process_maybe_execute_sell                                                                                                                 │······································································
    result = self.handle_trade(trade)                                                                                                                                                                              │······································································
  File "/home/ubuntu/freqtrade/freqtrade/freqtradebot.py", line 604, in handle_trade                                                                                                                               │······································································
    sell_rate = self.get_sell_rate(trade.pair, True)                                                                                                                                                               │······································································
  File "/home/ubuntu/freqtrade/freqtrade/freqtradebot.py", line 565, in get_sell_rate                                                                                                                              │······································································
    rate = self.exchange.get_ticker(pair, refresh)['bid']                                                                                                                                                          │······································································
  File "/home/ubuntu/freqtrade/freqtrade/exchange/exchange.py", line 52, in wrapper                                                                                                                                │······································································
    return f(*args, **kwargs)                                                                                                                                                                                      │······································································
  File "/home/ubuntu/freqtrade/freqtrade/exchange/exchange.py", line 520, in get_ticker                                                                                                                            │······································································
    data = self._api.fetch_ticker(pair)                                                                                                                                                                            │······································································
  File "/home/ubuntu/freqtrade/.env/lib/python3.6/site-packages/ccxt/bittrex.py", line 502, in fetch_ticker                                                                                                        │······································································
    return self.parse_ticker(ticker, market)                                                                                                                                                                       │······································································
  File "/home/ubuntu/freqtrade/.env/lib/python3.6/site-packages/ccxt/bittrex.py", line 375, in parse_ticker                                                                                                        │······································································
    timestamp = self.parse8601(self.safe_string(ticker, 'TimeStamp'))                                                                                                                                              │······································································
  File "/home/ubuntu/freqtrade/.env/lib/python3.6/site-packages/ccxt/base/exchange.py", line 607, in safe_string                                                                                                   │······································································
    return str(dictionary[key]) if key is not None and (key in dictionary) and dictionary[key] is not None else default_value                                                                                      │······································································
TypeError: argument of type 'NoneType' is not iterable    
`

**Comment by xmatthias** [comment]
i would suggest to open a new issue - comments on issues to 2 year old issues are commonly overlooked (and even though the exception is the same, the cause is surely not, also because the stacktrace is different.
