### ISSUE TITLE
Buy resulting in crash of loop

### ISSUE THREAD

**Issue by phacts** [gcarq/freqtrade#106]
This is in the `develop` branch, which I've had running overnight with `"dry_run": true`.

A number of buy/sell orders were placed overnight, but one of them caused an error that killed the loop.  Note that the pair BTC-LUN was successfully bought and sold overnight, so it's not like this is unique to this coin pairing.  Anyway, here is the error I'm seeing in the console:

```
2017-11-15 12:14:48,532 - freqtrade - INFO - Checking buy signals to create a new trade with stake_amount: 0.050000 ...
2017-11-15 12:14:58,986 - freqtrade - INFO - *BITTREX:* Buying [BTC/LUN](https://www.bittrex.com/Market/Index?MarketName=BTC-LUN) with limit `0.00065566`
2017-11-15 12:15:00,378 - freqtrade - INFO - Got open order for Trade(id=5, pair=BTC_LUN, amount=76.06838910410885, open_rate=0.00065566, open_since=just now)
Traceback (most recent call last):
  File "./freqtrade/main.py", line 361, in <module>
    main()
  File "./freqtrade/main.py", line 355, in main
    dynamic_whitelist=args.dynamic_whitelist,
  File "/Users/sgrimm/dev/cryptos/bots/freqtrade/freqtrade/misc.py", line 52, in throttle
    result = func(*args, **kwargs)
  File "./freqtrade/main.py", line 91, in _process
    state_changed = handle_trade(trade) or state_changed
  File "./freqtrade/main.py", line 181, in handle_trade
    current_rate = exchange.get_ticker(trade.pair)['bid']
  File "/Users/sgrimm/dev/cryptos/bots/freqtrade/freqtrade/exchange/__init__.py", line 128, in get_ticker
    return _API.get_ticker(pair)
  File "/Users/sgrimm/dev/cryptos/bots/freqtrade/freqtrade/exchange/bittrex.py", line 85, in get_ticker
    if not data['result']['Bid'] or not data['result']['Ask'] or not data['result']['Last']:
TypeError: 'NoneType' object is not subscriptable
2
```

**Comment by flightcom** [comment]
I just had the same error using `0.14.2`

**Comment by sambrainus** [comment]
for i in range(1,10000):
    print ("\nConnection attempt number : ",i)
    try:       
        while True :
                 
                   (put your bot here)
    except TypeError:
        msg = "\nYou probably lost connection, connect and try again\n"
        print(msg)
    time.sleep(10)


this trick will let you know if you lost connection and tries to reconnect your bot after 10 s (you can adjust the sleep time.
