### ISSUE TITLE
Pair not available

### ISSUE THREAD

**Issue by dignus81** [gcarq/freqtrade#120]
Running 0.14.2 as docker image results in these logs after starting up:

```
2017-11-20 09:33:48,057 - freqtrade - INFO - Starting freqtrade 0.14.2 (loglevel=INFO)
2017-11-20 09:33:48,058 - freqtrade - INFO - Validating configuration ...
2017-11-20 09:33:48,065 - freqtrade.rpc.telegram - INFO - rpc.telegram is listening for following commands: [['status'], ['profit'], ['balance'], ['start'], ['stop'], ['forcesell'], ['performance'], ['count'], ['help'], ['version']]
```

Then it idles. When executing /status:

```
Traceback (most recent call last):
  File "/usr/local/bin/freqtrade", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/freqtrade/bin/freqtrade", line 4, in <module>
    main()
  File "/freqtrade/freqtrade/main.py", line 340, in main
    init(_CONF)
  File "/freqtrade/freqtrade/main.py", line 265, in init
    exchange.init(config)
  File "/freqtrade/freqtrade/exchange/__init__.py", line 56, in init
    validate_pairs(config['exchange']['pair_whitelist'])
  File "/freqtrade/freqtrade/exchange/__init__.py", line 74, in validate_pairs
    raise RuntimeError('Pair {} is not available at {}'.format(pair, _API.name.lower()))
RuntimeError: Pair BTC-ADX is not available at bittrex
2017-11-20 09:34:00,377 - freqtrade.rpc.telegram - INFO - Executing handler: _status for chat_id:
```

This is for every coin I set in the config.

**Comment by baudbox** [comment]
I guess because you must separate not with a dash (BTC-ADX) but by an underscore (BTC_ADX)

**Comment by gcarq** [comment]
As @baudbox already mentioned it should work with underscore. We should implement a validation for this.
