### ISSUE TITLE
ValueError: negative dimensions are not allowed in awesome_oscillator

### ISSUE THREAD

**Issue by gcarq** [gcarq/freqtrade#123]
```
Traceback (most recent call last):
  File "/usr/bin/freqtrade", line 4, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/freqtrade/main.py", line 329, in main
    dynamic_whitelist=args.dynamic_whitelist,
  File "/usr/lib/python3.6/site-packages/freqtrade/misc.py", line 81, in throttle
    result = func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/freqtrade/main.py", line 70, in _process
    trade = create_trade(float(_CONF['stake_amount']))
  File "/usr/lib/python3.6/site-packages/freqtrade/main.py", line 202, in create_trade
    if get_signal(_pair, SignalType.BUY):
  File "/usr/lib/python3.6/site-packages/freqtrade/analyze.py", line 122, in get_signal
    dataframe = analyze_ticker(pair)
  File "/usr/lib/python3.6/site-packages/freqtrade/analyze.py", line 107, in analyze_ticker
    dataframe = populate_indicators(dataframe)
  File "/usr/lib/python3.6/site-packages/freqtrade/analyze.py", line 56, in populate_indicators
    dataframe['ao'] = awesome_oscillator(dataframe)
  File "/usr/lib/python3.6/site-packages/freqtrade/vendor/qtpylib/indicators.py", line 156, in awesome_oscillator
    numpy_rolling_mean(midprice, slow)
  File "/usr/lib/python3.6/site-packages/freqtrade/vendor/qtpylib/indicators.py", line 52, in func_wrapper
    calculated = func(series, window)
  File "/usr/lib/python3.6/site-packages/freqtrade/vendor/qtpylib/indicators.py", line 65, in numpy_rolling_mean
    return np.mean(numpy_rolling_window(data, window), -1)
  File "/usr/lib/python3.6/site-packages/freqtrade/vendor/qtpylib/indicators.py", line 44, in numpy_rolling_window
    return np.lib.stride_tricks.as_strided(data, shape=shape, strides=strides)
  File "/usr/lib/python3.6/site-packages/numpy/lib/stride_tricks.py", line 102, in as_strided
    array = np.asarray(DummyArray(interface, base=x))
  File "/usr/lib/python3.6/site-packages/numpy/core/numeric.py", line 531, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: negative dimensions are not allowed
```

Somehow the data provided by `get_ticker_history` seems to be invalid (maybe it contains some null values).
It is also sometimes reproducible with `$ bin/freqtrade backtesting --live`

**Comment by gcarq** [comment]
Seems like bittrex enabled BTC_BTG and it only has a history of 25 entries, as far as I can see awesome_oscillator requires at least 34 data points.

**Comment by vertti** [comment]
The indicators we took from qtpylib have no unit tests and seem to break if you don't give them exactly what they want, like long enough data series. They are looking for help on that 😆  https://github.com/ranaroussi/qtpylib/issues/62
