### ISSUE TITLE
APIKEY_INVALID 

### ISSUE THREAD

**Issue by chrisapril** [gcarq/freqtrade#144]
Hi,

i got this exception with the develop branch afte running the bot for 6 hours:

2017-11-25 03:19:02,973 - freqtrade.rpc - INFO - *Status:* Got OperationalException:
```
Traceback (most recent call last):
  File "./freqtrade/main.py", line 70, in _process
    state_changed = create_trade(float(_CONF['stake_amount']))
  File "./freqtrade/main.py", line 186, in create_trade
    if exchange.get_balance(_CONF['stake_currency']) < stake_amount:
  File "/home/pi/pythons/freqtrade-prod/freqtrade/exchange/__init__.py", line 127, in get_balance
    return _API.get_balance(currency)
  File "/home/pi/pythons/freqtrade-prod/freqtrade/exchange/bittrex.py", line 72, in get_balance
    currency=currency))
freqtrade.OperationalException: APIKEY_INVALID params=(BTC)
```Issue `/start` if you think it is safe to restart.
2017-11-25 03:19:03,200 - freqtrade - ERROR - Got OperationalException. Stopping trader ...
Traceback (most recent call last):
  File "./freqtrade/main.py", line 70, in _process
    state_changed = create_trade(float(_CONF['stake_amount']))
  File "./freqtrade/main.py", line 186, in create_trade
    if exchange.get_balance(_CONF['stake_currency']) < stake_amount:
  File "/home/pi/pythons/freqtrade-prod/freqtrade/exchange/__init__.py", line 127, in get_balance
    return _API.get_balance(currency)
  File "/home/pi/pythons/freqtrade-prod/freqtrade/exchange/bittrex.py", line 72, in get_balance
    currency=currency))
freqtrade.OperationalException: APIKEY_INVALID params=(BTC)
2017-11-25 03:19:07,196 - freqtrade.rpc - INFO - *Status:* `stopped`
2017-11-25 03:19:07,247 - freqtrade - INFO - Changing state to: STOPPED


After restarting the bot (with /start), everything was fine.

**Comment by shusso** [comment]
@chrisapril what do you have in `pair_whitelist` in config.json?

**Comment by chrisapril** [comment]
"pair_whitelist": [
            "BTC_BTG",
            "BTC_POWR",
            "BTC_NEO",
            "BTC_ETH",
            "BTC_DASH",
            "BTC_BCC",
            "BTC_POT",
            "BTC_NXT",
            "BTC_MTL",
            "BTC_GRS",
            "BTC_LSK",
            "BTC_XRP",
            "BTC_XZC",
            "BTC_LTC",
            "BTC_PAY",
            "BTC_FTC",
            "BTC_OMG",
            "BTC_ADA",
            "BTC_CLUB",
            "BTC_VTC",
            "BTC_QTUM",
            "BTC_ADX",
            "BTC_STRAT",
            "BTC_ETC",
            "BTC_TRIG",
            "BTC_XLM",
            "BTC_SLR",
            "BTC_XMR",
            "BTC_ZEC",
            "BTC_CVC",
            "BTC_STORJ",
            "BTC_EMC2",
            "BTC_OK",
            "BTC_WAVES",
            "BTC_ARDR",
            "BTC_XVG",
            "BTC_MER",
            "BTC_SNT",
            "BTC_XEM",
            "BTC_KMD",
            "BTC_MCO",
            "BTC_ARK",
            "BTC_ZEN",
            "BTC_SALT",
            "BTC_CANN",
            "BTC_DCT",
            "BTC_FCT",
            "BTC_PIVX",
            "BTC_DTB",
            "BTC_DGB",
            "BTC_BAT",
            "BTC_BAY",
            "BTC_NAV",
            "BTC_RCN",
            "BTC_GNT",
            "BTC_MONA",
            "BTC_SC",
            "BTC_DNT",
            "BTC_BLK",
            "BTC_SYS",
            "BTC_STEEM",
            "BTC_FUN",
            "BTC_PTOY",
            "BTC_SWT",
            "BTC_TRST"
        ]

**Comment by chrisapril** [comment]
I thin the problem was a not completed order:

....
2017-11-25 05:26:52,016 - freqtrade - INFO - Got open order for Trade(id=6, pair=BTC_ARDR, amount=159.13430936, open_rate=0.00003142, open_since=5 hours ago)
2017-11-25 05:26:55,046 - freqtrade.rpc.telegram - INFO - Executing handler: _count for chat_id: -284843235
2017-11-25 05:26:56,994 - freqtrade - INFO - Got open order for Trade(id=6, pair=BTC_ARDR, amount=159.13430936, open_rate=0.00003142, open_since=5 hours ago)
2017-11-25 05:27:03,164 - freqtrade - INFO - Got open order for Trade(id=6, pair=BTC_ARDR, amount=159.13430936, open_rate=0.00003142, open_since=5 hours ago)
.....

The status of the order was polled every few seconds. My guess is, that this was the reason that i got this error from bittrex.

**Comment by shusso** [comment]
Relates to #66

**Comment by shusso** [comment]
Closing per #229
