### ISSUE TITLE
TypeError: conversion from NoneType to Decimal is not supported

### ISSUE THREAD

**Issue by chrisapril** [gcarq/freqtrade#145]
Hi,

i got an  unfilled order and i cancelled it manually. After that i got this exception:

```
2017-11-25 05:26:52,016 - freqtrade - INFO - Got open order for Trade(id=6, pair=BTC_ARDR, amount=159.13430936, open_rate=0.00003142, open_since=5 hours ago)
2017-11-25 05:26:55,046 - freqtrade.rpc.telegram - INFO - Executing handler: _count for chat_id: -284843235
2017-11-25 05:26:56,994 - freqtrade - INFO - Got open order for Trade(id=6, pair=BTC_ARDR, amount=159.13430936, open_rate=0.00003142, open_since=5 hours ago)
2017-11-25 05:27:03,164 - freqtrade - INFO - Got open order for Trade(id=6, pair=BTC_ARDR, amount=159.13430936, open_rate=0.00003142, open_since=5 hours ago)
2017-11-25 05:27:03,505 - freqtrade.persistence - INFO - Updating trade (id=6) ...
--- Logging error ---
Traceback (most recent call last):
  File "/home/pi/berryconda3/envs/freqtrade/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/home/pi/berryconda3/envs/freqtrade/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/home/pi/berryconda3/envs/freqtrade/lib/python3.6/logging/__init__.py", line 575, in format
    record.message = record.getMessage()
  File "/home/pi/berryconda3/envs/freqtrade/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
  File "/home/pi/pythons/freqtrade-prod/freqtrade/persistence.py", line 76, in __repr__
    arrow.get(self.open_date).humanize() if self.is_open else 'closed'
TypeError: unsupported format string passed to NoneType.__format__
Call stack:
  File "./freqtrade/main.py", line 342, in <module>
    main()
  File "./freqtrade/main.py", line 330, in main
    dynamic_whitelist=args.dynamic_whitelist,
  File "/home/pi/pythons/freqtrade-prod/freqtrade/misc.py", line 77, in throttle
    result = func(*args, **kwargs)
  File "./freqtrade/main.py", line 84, in _process
    trade.update(exchange.get_order(trade.open_order_id))
  File "/home/pi/pythons/freqtrade-prod/freqtrade/persistence.py", line 93, in update
    logger.info('LIMIT_BUY has been fulfilled for %s.', self)
Unable to print the message and arguments - possible formatting error.
Use the traceback above to help find the error.
2017-11-25 05:27:04,385 - freqtrade - ERROR - Got fatal exception!
Traceback (most recent call last):
  File "./freqtrade/main.py", line 330, in main
    dynamic_whitelist=args.dynamic_whitelist,
  File "/home/pi/pythons/freqtrade-prod/freqtrade/misc.py", line 77, in throttle
    result = func(*args, **kwargs)
  File "./freqtrade/main.py", line 88, in _process
    state_changed = handle_trade(trade) or state_changed
  File "./freqtrade/main.py", line 159, in handle_trade
    if min_roi_reached(trade, current_rate, datetime.utcnow()) or get_signal(trade.pair, SignalType.SELL):
  File "./freqtrade/main.py", line 134, in min_roi_reached
    current_profit = trade.calc_profit(current_rate)
  File "/home/pi/pythons/freqtrade-prod/freqtrade/persistence.py", line 118, in calc_profit
    return float((Decimal(rate or self.close_rate) - Decimal(self.open_rate))
TypeError: conversion from NoneType to Decimal is not supported
2017-11-25 05:27:04,389 - freqtrade.rpc - INFO - *Status:* `Stopping trader...`
```

When i tried to restart the bot, i got this Exception:

```
2017-11-25 05:28:15,147 - freqtrade - INFO - Starting freqtrade 0.14.3 (loglevel=INFO)
2017-11-25 05:28:15,148 - freqtrade.misc - INFO - Validating configuration ...
2017-11-25 05:28:15,180 - freqtrade.rpc - INFO - Enabling rpc.telegram ...
2017-11-25 05:28:15,187 - freqtrade.rpc.telegram - INFO - rpc.telegram is listening for following commands: [['status'], ['profit'], ['balance'], ['start'], ['stop'], ['forcesell'], ['performance'], ['count'], ['help'], ['version']]
2017-11-25 05:28:15,477 - freqtrade.rpc - INFO - *Status:* `running`
2017-11-25 05:28:15,545 - freqtrade - INFO - Changing state to: RUNNING
2017-11-25 05:28:16,636 - freqtrade - ERROR - Got fatal exception!
Traceback (most recent call last):
  File "./freqtrade/main.py", line 330, in main
    dynamic_whitelist=args.dynamic_whitelist,
  File "/home/pi/pythons/freqtrade-prod/freqtrade/misc.py", line 77, in throttle
    result = func(*args, **kwargs)
  File "./freqtrade/main.py", line 88, in _process
    state_changed = handle_trade(trade) or state_changed
  File "./freqtrade/main.py", line 159, in handle_trade
    if min_roi_reached(trade, current_rate, datetime.utcnow()) or get_signal(trade.pair, SignalType.SELL):
  File "./freqtrade/main.py", line 134, in min_roi_reached
    current_profit = trade.calc_profit(current_rate)
  File "/home/pi/pythons/freqtrade-prod/freqtrade/persistence.py", line 118, in calc_profit
    return float((Decimal(rate or self.close_rate) - Decimal(self.open_rate))
TypeError: conversion from NoneType to Decimal is not supported
2017-11-25 05:28:16,640 - freqtrade.rpc - INFO - *Status:* `Stopping trader...`
2017-11-25 05:28:16,816 - freqtrade - INFO - Stopping trader and cleaning up modules...
```

**Comment by chrisapril** [comment]
And can somone help how i can restart the bot? Do i have to delete the sqllite DB manually?

**Comment by baudbox** [comment]
> Do i have to delete the sqllite DB manually?

Yes and no. You have to remove only the order id that you've canceled manually. For either you know the correct order id to remove, or you can identify it by this query
`sqlite3 tradesv3.sqlite "select * from trades;"`

Here is an output
```
...
23|BITTREX|BTC_TRST|1|0.005|3.84e-05|||0.0015|39.05233012|2017-11-25 09:06:48.710821||
```

The number at the very beginning of the line is the trade id to remove. I guess for you it's the last one.
(oh, make a backup of the db before in any case). Then do this query to remove the order

`sqlite3 tradesv3.sqlite "delete from trades where id = 23;"`

I guess you can restart the bot afterwards

> When an order is not filled since several hours, how do you cancl the order? Do you use /forcesell <trade_id>|all ?

If you need to yes, check the id of the order again by /status, then do a /forcesell <trade_id>

**Comment by shusso** [comment]
Closing per #229

**Comment by kzaky** [comment]
Had a similar issue you just have to delete the trade manual from the db. You just need to know the trade id

```sql
sqlite3 tradesv3.sqlite "delete from trades where id = 1;"
```
