### ISSUE TITLE
ZeroDivisionError after /count

### ISSUE THREAD

**Issue by chrisapril** [gcarq/freqtrade#147]
2017-11-26 19:38:49,167 - freqtrade.rpc.telegram - INFO - Executing handler: _count for chat_id: -284843235
2017-11-26 19:38:49,178 - freqtrade.rpc.telegram - DEBUG - <pre>  current    max
---------  -----
        8     10</pre>
2017-11-26 19:39:08,160 - freqtrade.rpc.telegram - INFO - Executing handler: _profit for chat_id: XXX
2017-11-26 19:39:31,733 - freqtrade.rpc.telegram - ERROR - Exception occurred within Telegram module
Traceback (most recent call last):
  File "/home/pi/pythons/freqtrade-prod/freqtrade/rpc/telegram.py", line 104, in wrapper
    return command_handler(*args, **kwargs)
  File "/home/pi/pythons/freqtrade-prod/freqtrade/rpc/telegram.py", line 263, in _profit
    avg_duration=str(timedelta(seconds=sum(durations) / float(len(durations)))).split('.')[0],
ZeroDivisionError: float division by zero

**Comment by vertti** [comment]
Thanks for reporting this.

**Comment by jblestang** [comment]
Cannot be reproduced with the latest version of develop , the refactoring made by @glonlas on the _profit function to add FIAT have added an early return that prevent the bug from happening again

**Comment by glonlas** [comment]
I do not reproduce as well.
I will close this issue. Feel free to reopen it if you have the issue.
