### ISSUE TITLE
Getting error after manually removing a old trade that the bot made

### ISSUE THREAD

**Issue by devalias** [gcarq/freqtrade#153]
Hi, I'm running on the develop branch, I removed an old entry the bot made and now it keeps crashing with:

2017-12-01 08:54:45,120 - freqtrade - ERROR - Got fatal exception!
Traceback (most recent call last):
  File "./freqtrade/main.py", line 339, in main
    dynamic_whitelist=args.dynamic_whitelist,
  File "/home/osboxes/freqtrade/.env/lib/python3.6/site-packages/freqtrade-0.14.3-py3.6.egg/freqtrade/misc.py", line 77, in throttle
    result = func(*args, **kwargs)
  File "./freqtrade/main.py", line 88, in _process
    state_changed = handle_trade(trade) or state_changed
  File "./freqtrade/main.py", line 161, in handle_trade
    if not min_roi_reached(trade, current_rate, datetime.utcnow()):
  File "./freqtrade/main.py", line 134, in min_roi_reached
    current_profit = trade.calc_profit(current_rate)
  File "/home/osboxes/freqtrade/.env/lib/python3.6/site-packages/freqtrade-0.14.3-py3.6.egg/freqtrade/persistence.py", line 118, in calc_profit
    return float((Decimal(rate or self.close_rate) - Decimal(self.open_rate))
TypeError: conversion from NoneType to Decimal is not supported
2017-12-01 08:54:45,124 - freqtrade.rpc - INFO - *Status:* `Stopping trader...`
2017-12-01 08:54:45,736 - freqtrade - INFO - Stopping trader and cleaning up modules...

**Comment by chrisapril** [comment]
Hi, i had the same problem:

https://github.com/gcarq/freqtrade/issues/145

I think we need a mechanism to remove not filled buy orders. And perhaps a configuration which autodelete not filled buy orders after a defined amount of time.

**Comment by shusso** [comment]
relates to #66 and #144

**Comment by shusso** [comment]
Closing per #229
