### ISSUE TITLE
Unable to start the bot received Fatal Exception

### ISSUE THREAD

**Issue by cryptophunk** [gcarq/freqtrade#167]
Whenever I try to run the bot an exception was thrown.

`2017-12-08 13:06:23,051 - freqtrade - INFO - Starting freqtrade 0.14.3 (loglevel=INFO)
2017-12-08 13:06:23,052 - freqtrade.misc - INFO - Validating configuration ...
2017-12-08 13:06:23,056 - freqtrade.rpc - INFO - Enabling rpc.telegram ...
2017-12-08 13:06:23,057 - freqtrade.rpc.telegram - INFO - rpc.telegram is listening for following commands: [['status'], ['profit'], ['balance'], ['start'], ['stop'], ['forcesell'], ['performance'], ['count'], ['help'], ['version']]
2017-12-08 13:06:23,100 - freqtrade.rpc - INFO - *Status:* `running`
2017-12-08 13:06:24,483 - freqtrade - INFO - Changing state to: RUNNING
2017-12-08 13:06:24,684 - freqtrade - INFO - Ignoring BTC_NAV from whitelist (reason: Automated Maintenance.).
2017-12-08 13:06:24,685 - freqtrade - INFO - Ignoring BTC_IOC from whitelist (reason: IOC wallet disabled while network upgrade in progress).
2017-12-08 13:06:24,685 - freqtrade - INFO - Ignoring BTC_XRP from whitelist (reason: Wallet Disabled - performing routine maintenance).
2017-12-08 13:06:24,685 - freqtrade - INFO - Ignoring BTC_AMP from whitelist (reason: Wallet Maintenance).
2017-12-08 13:06:24,685 - freqtrade - INFO - Ignoring BTC_AGRS from whitelist (reason: Wallet Maintenance).
2017-12-08 13:06:24,685 - freqtrade - INFO - Ignoring BTC_SAFEX from whitelist (reason: Wallet Maintenance).
2017-12-08 13:06:24,685 - freqtrade - INFO - Ignoring BTC_PDC from whitelist (reason: Wallet Maintenance).
2017-12-08 13:06:24,686 - freqtrade - INFO - Ignoring BTC_ARK from whitelist (reason: Wallet Disabled - performing routine maintenance).
2017-12-08 13:06:24,686 - freqtrade - INFO - Ignoring BTC_DYN from whitelist (reason: Wallet Offline - Dev requested).
2017-12-08 13:06:24,927 - freqtrade - ERROR - Got fatal exception!
Traceback (most recent call last):
  File "./freqtrade/main.py", line 339, in main
    dynamic_whitelist=args.dynamic_whitelist,
  File "/home/ubuntu/hft/0.14.3/dev_branch/freqtrade/freqtrade/misc.py", line 76, in throttle
    result = func(*args, **kwargs)
  File "./freqtrade/main.py", line 88, in _process
    state_changed = handle_trade(trade) or state_changed
  File "./freqtrade/main.py", line 161, in handle_trade
    if not min_roi_reached(trade, current_rate, datetime.utcnow()):
  File "./freqtrade/main.py", line 134, in min_roi_reached
    current_profit = trade.calc_profit(current_rate)
  File "/home/ubuntu/hft/0.14.3/dev_branch/freqtrade/freqtrade/persistence.py", line 118, in calc_profit
    return float((Decimal(rate or self.close_rate) - Decimal(self.open_rate))
TypeError: conversion from NoneType to Decimal is not supported
2017-12-08 13:06:24,928 - freqtrade.rpc - INFO - *Status:* `Stopping trader...`
2017-12-08 13:06:25,484 - freqtrade - INFO - Stopping trader and cleaning up modules...`

**Comment by cryptophunk** [comment]
Got it fixed by emptying the trades table could be something to do with the previous records in the trades table.
