### ISSUE TITLE
Fatal Exception! Invalid Telegram Token

### ISSUE THREAD

**Issue by Nabk6** [gcarq/freqtrade#179]
I can't figure out the issue, I've tried replacing the telegram token 3 times here's the code.

```
2017-12-13 19:43:25,019 - freqtrade - INFO - Starting freqtrade 0.14.3 (loglevel=INFO)
2017-12-13 19:43:25,020 - freqtrade.misc - INFO - Validating configuration ...
2017-12-13 19:43:25,023 - freqtrade.rpc - INFO - Enabling rpc.telegram ...
2017-12-13 19:43:25,023 - freqtrade - ERROR - Got fatal exception!
Traceback (most recent call last):
  File "./freqtrade/main.py", line 329, in main
    init(_CONF)
  File "./freqtrade/main.py", line 252, in init
    rpc.init(config)
  File "/Users/NoahAbecassis/freqtrade/freqtrade/rpc/__init__.py", line 21, in init
    telegram.init(config)
  File "/Users/NoahAbecassis/freqtrade/freqtrade/rpc/telegram.py", line 41, in init
    _UPDATER = Updater(token=config['telegram']['token'], workers=0)
  File "/Users/NoahAbecassis/freqtrade/.env/lib/python3.6/site-packages/telegram/ext/updater.py", line 122, in __init__
    self.bot = Bot(token, base_url, request=self._request)
  File "/Users/NoahAbecassis/freqtrade/.env/lib/python3.6/site-packages/telegram/bot.py", line 108, in __init__
    self.token = self._validate_token(token)
  File "/Users/NoahAbecassis/freqtrade/.env/lib/python3.6/site-packages/telegram/bot.py", line 134, in _validate_token
    raise InvalidToken()
telegram.error.InvalidToken: Invalid token
2017-12-13 19:43:25,025 - freqtrade.rpc - INFO - *Status:* `Stopping trader...`
Traceback (most recent call last):
  File "./freqtrade/main.py", line 356, in <module>
    main()
  File "./freqtrade/main.py", line 352, in main
    cleanup()
  File "./freqtrade/main.py", line 291, in cleanup
    rpc.send_msg('*Status:* `Stopping trader...`')
  File "/Users/NoahAbecassis/freqtrade/freqtrade/rpc/__init__.py", line 42, in send_msg
    telegram.send_msg(msg)
  File "/Users/NoahAbecassis/freqtrade/freqtrade/rpc/telegram.py", line 519, in send_msg
    bot = bot or _UPDATER.bot
AttributeError: 'NoneType' object has no attribute 'bot'
(.env) Noahs-MacBook-Pro:freqtrade NoahAbecassis$ 
```

EDIT: Updated exception formatting

**Comment by gcarq** [comment]
How did you get your telegram token? See https://core.telegram.org/bots/api#authorizing-your-bot and check if your format matches the expected format.

**Comment by glonlas** [comment]
Hi @Nabk6 have you resolved your issue?

**Comment by Nabk6** [comment]
Yeah I copied my key wrong...dumb mistake

**Comment by glonlas** [comment]
@gcarq issue resolved
