### ISSUE TITLE
freqtrade.OperationalException: APIKEY_INVALID params=(BTC)

### ISSUE THREAD

**Issue by seansan** [gcarq/freqtrade#207]
Run into error on clean install

I read `line 84, in get_balance
    currency=currency))
freqtrade.OperationalException: APIKEY_INVALID params=(BTC)``

but wondering if really APIKEY_INVALID 
or
the balance = 0 (which is true)

How does freqtrade handle balance = 0? or at least < stake_trade?

```
```
(.env) [root@bitbot freqtrade]# python3.6 ./freqtrade/main.py
2017-12-19 20:43:50,733 - freqtrade - INFO - Starting freqtrade 0.14.3 (loglevel=INFO)
2017-12-19 20:43:50,734 - freqtrade.misc - INFO - Validating configuration ...
2017-12-19 20:43:50,741 - freqtrade.rpc - INFO - Enabling rpc.telegram ...
2017-12-19 20:43:50,746 - freqtrade.rpc.telegram - INFO - rpc.telegram is listening for following commands: [['status'], ['profit'], ['balance'], ['start'], ['stop'], ['forcesell'], ['performance'], ['daily'], ['count'], ['help'], ['version']]
2017-12-19 20:43:50,823 - freqtrade.rpc - INFO - *Status:* `running`
2017-12-19 20:43:50,884 - freqtrade - INFO - Changing state to: RUNNING
2017-12-19 20:43:50,933 - freqtrade - INFO - Checking buy signals to create a new trade with stake_amount: 0.050000 ...
2017-12-19 20:43:52,193 - freqtrade.rpc - INFO - *Status:* Got OperationalException:
```
Traceback (most recent call last):
  File "./freqtrade/main.py", line 73, in _process
    state_changed = create_trade(float(_CONF['stake_amount']))
  File "./freqtrade/main.py", line 198, in create_trade
    if exchange.get_balance(_CONF['stake_currency']) < stake_amount:
  File "/var/www/freqtrade/freqtrade/exchange/__init__.py", line 127, in get_balance
    return _API.get_balance(currency)
  File "/var/www/freqtrade/freqtrade/exchange/bittrex.py", line 84, in get_balance
    currency=currency))
freqtrade.OperationalException: APIKEY_INVALID params=(BTC)
```Issue `/start` if you think it is safe to restart.
2017-12-19 20:43:52,223 - freqtrade - ERROR - Got OperationalException. Stopping trader ...
Traceback (most recent call last):
  File "./freqtrade/main.py", line 73, in _process
    state_changed = create_trade(float(_CONF['stake_amount']))
  File "./freqtrade/main.py", line 198, in create_trade
    if exchange.get_balance(_CONF['stake_currency']) < stake_amount:
  File "/var/www/freqtrade/freqtrade/exchange/__init__.py", line 127, in get_balance
    return _API.get_balance(currency)
  File "/var/www/freqtrade/freqtrade/exchange/bittrex.py", line 84, in get_balance
    currency=currency))
freqtrade.OperationalException: APIKEY_INVALID params=(BTC)
2017-12-19 20:43:55,889 - freqtrade.rpc - INFO - *Status:* `stopped`
2017-12-19 20:43:55,915 - freqtrade - INFO - Changing state to: STOPPED
```

```

**Comment by chromafunk** [comment]
I just had this error thrown at me when trying to sell ... is there an explanation of why it happens ?
