### ISSUE TITLE
INSUFFICIENT_FUNDS error

### ISSUE THREAD

**Issue by seansan** [gcarq/freqtrade#219]
Using master. Ran into INSUFFICIENT_FUNDS error
Problem is twofold
- it stopped the bot (should not do that)
- does it not check funds adequately before making a trade, hence not running into this error

ref https://github.com/gcarq/freqtrade/issues/102

Status: Got OperationalException:
Traceback (most recent call last):
  File "/var/www/freqtrade/freqtrade/main.py", line 73, in _process
    state_changed = create_trade(float(_CONF['stake_amount']))
  File "/var/www/freqtrade/freqtrade/main.py", line 223, in create_trade
    order_id = exchange.buy(pair, buy_limit, amount)
  File "/var/www/freqtrade/freqtrade/exchange/__init__.py", line 102, in buy
    return _API.buy(pair, rate, amount)
  File "/var/www/freqtrade/freqtrade/exchange/bittrex.py", line 64, in buy
    amount=amount))
freqtrade.OperationalException: INSUFFICIENT_FUNDS params=(BTC_XMR, 0.0267, 0.749063670411985)
Issue /start if you think it is safe to restart.

**Comment by seansan** [comment]
Problem with this bug is that it kills the bot - often when you have many trades outstanding
Next time (or morning) you have a look it is always a small sell  party when the bot starts acting after hours with open trades ... often with losses/wins

**Comment by seansan** [comment]
Seeing this again. BTC_XVG .... my wallet has enough for this buy. Does the bot think I still have XVG and is trying to sell it?

**Comment by seansan** [comment]
Only thing to improve now is: it should not crash the bot, just inform ... 
(maybe after close issue)

**Comment by shusso** [comment]
Plesse re-open if problem persists

**Comment by MiHaDevs** [comment]
Got OperationalException:
Traceback (most recent call last):
  File "./freqtrade/main.py", line 124, in _process
    state_changed = process_maybe_execute_buy(interval)
  File "./freqtrade/main.py", line 65, in process_maybe_execute_buy
    if create_trade(float(_CONF['stake_amount']), interval):
  File "./freqtrade/main.py", line 407, in create_trade
    order_id = exchange.buy(pair, buy_limit, amount)
  File "/home/ubuntu/freqtrade/freqtrade/exchange/__init__.py", line 102, in buy
    return _API.buy(pair, rate, amount)
  File "/home/ubuntu/freqtrade/freqtrade/exchange/bittrex.py", line 70, in buy
    amount=amount))
freqtrade.OperationalException: INSUFFICIENT_FUNDS params=(BTC_NEO, 0.01327171, 0.03767412036580064)

I tried starting it again but it stops with the same exception over and over again.

**Comment by chromafunk** [comment]
This just happened to me today ... killing the process and restarting does the trick
