### ISSUE TITLE
error in /performance command since latest develop version 28-12-17

### ISSUE THREAD

**Issue by seansan** [gcarq/freqtrade#251]
error in /performance command since latest develop version 28-12-17

:```
 2017-12-28 19:36:48,096 - freqtrade.rpc.telegram - INFO - Executing handler: _performance for chat_id: 1234
: 2017-12-28 19:36:48,099 - freqtrade.rpc.telegram - ERROR - Exception occurred within Telegram module
: Traceback (most recent call last):
: File "/var/www/freqtrade/freqtrade/rpc/telegram.py", line 108, in wrapper
: return command_handler(*args, **kwargs)
: File "/var/www/freqtrade/freqtrade/rpc/telegram.py", line 483, in _performance
: ) for i, (pair, rate) in enumerate(pair_rates))
: File "/var/www/freqtrade/freqtrade/rpc/telegram.py", line 483, in <genexpr>
: ) for i, (pair, rate) in enumerate(pair_rates))
: TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
```

**Comment by seansan** [comment]
+1 confirmed 31-12 after latest pull

**Comment by shusso** [comment]
@seansan is this in master or develop? For me I was not able to repro this in the latest develop

**Comment by seansan** [comment]
just pulled last develop
same error

is pair_rates coming from CB? malformed data? or is that not possible

**Comment by seansan** [comment]
@shusso I had an idea that this was DB related. There are some trades with status = 0 (closed) ... .without an END DATE (column) empty .... I ran delete from trades where id =12; to delete that line and it worked again .... 
in sjort: not sure it is a real error, but question is if it should "hang" on missing data for closed trades..... maybe just omit them?

**Comment by ElanHasson** [comment]
I'm encountering this too with latest.

Is there a solution for this?

**Comment by seansan** [comment]
See my comment
Open the DB file; go to the table
And check for closed trades without end date (or other unexpected to calculate performance)
