### ISSUE TITLE
Got fatal exception unexpected keyword argument 'dynamic_whitelist'

### ISSUE THREAD

**Issue by pan-long** [gcarq/freqtrade#262]
Error message and trace:

2017-12-30 14:00:45,831 - freqtrade - ERROR - Got fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 382, in main
    dynamic_whitelist=args.dynamic_whitelist,
  File "/freqtrade/freqtrade/misc.py", line 76, in throttle
    result = func(*args, **kwargs)
TypeError: _process() got an unexpected keyword argument 'dynamic_whitelist'
2017-12-30 14:00:45,832 - freqtrade.rpc - INFO - *Status:* `Stopping trader...`
2017-12-30 14:00:45,833 - freqtrade - INFO - Stopping trader and cleaning up modules...

**Comment by gcarq** [comment]
Should be fixed with #263. Feel free to reopen if this is still an issue
