### ISSUE TITLE
cannot run /performance anymore - develop version 31-12

### ISSUE THREAD

**Issue by seansan** [gcarq/freqtrade#272]
cannot run /performance anymore - develop version 31-12

bot seems to continue though

Traceback (most recent call last):
Dec 31 16:26:06 bitbot python3.6[16459]: File "/var/www/freqtrade/freqtrade/rpc/telegram.py", line 108, in wrapper
Dec 31 16:26:06 bitbot python3.6[16459]: return command_handler(*args, **kwargs)
Dec 31 16:26:06 bitbot python3.6[16459]: File "/var/www/freqtrade/freqtrade/rpc/telegram.py", line 482, in _performance
Dec 31 16:26:06 bitbot python3.6[16459]: ) for i, (pair, rate) in enumerate(pair_rates))
Dec 31 16:26:06 bitbot python3.6[16459]: File "/var/www/freqtrade/freqtrade/rpc/telegram.py", line 482, in <genexpr>
Dec 31 16:26:06 bitbot python3.6[16459]: ) for i, (pair, rate) in enumerate(pair_rates))
Dec 31 16:26:06 bitbot python3.6[16459]: TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'

**Comment by seansan** [comment]
sorry dupe of #251
