### ISSUE TITLE
Error starting container: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 445: invalid start byte

### ISSUE THREAD

**Issue by ElanHasson** [gcarq/freqtrade#289]
I get this error in the log while attempting to start the container.

```

2018-01-02 18:13:32,084 - freqtrade - INFO - Starting freqtrade 0.14.3 (loglevel=INFO)
Traceback (most recent call last):
  File "/usr/local/bin/freqtrade", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/freqtrade/bin/freqtrade", line 4, in <module>
    main()
  File "/freqtrade/freqtrade/main.py", line 363, in main
    _CONF = load_config(args.config)
  File "/freqtrade/freqtrade/misc.py", line 53, in load_config
    conf = json.load(file)
  File "/usr/local/lib/python3.6/json/__init__.py", line 296, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 445: invalid start byte

```

**Comment by ElanHasson** [comment]
Whitespace in config.

In case anyone else gets this error.

**Comment by shusso** [comment]
Thanks for the heads up @ElanHasson 👍
