### ISSUE TITLE
Backtesting is failing to refresh testdata

### ISSUE THREAD

**Issue by rohit366** [gcarq/freqtrade#359]
(.env) C:\Users\Rohit.METRO-ROHIT\Desktop\freqtrade-develop\freqtrade>python main.py backtesting --realistic-simulation --refresh-pairs-cached
2018-01-11 12:53:24,978 - freqtrade.optimize.backtesting - INFO - Using config: config.json ...
2018-01-11 12:53:24,993 - freqtrade.misc - INFO - Validating configuration ...
2018-01-11 12:53:25,010 - freqtrade.optimize.backtesting - INFO - Using ticker_interval: 5 ...
2018-01-11 12:53:25,010 - freqtrade.optimize.backtesting - INFO - Using local backtesting data (using whitelist in given config) ...
2018-01-11 12:53:25,015 - freqtrade.optimize - INFO - Download data for all pairs and store them in freqtrade/tests/testdata
2018-01-11 12:53:25,022 - freqtrade.optimize - INFO - Download the pair: "BTC_XRP", Interval: 1 min
2018-01-11 12:53:36,919 - freqtrade.optimize - INFO - Failed to download the pair: "BTC_XRP", Interval: 1 min
2018-01-11 12:53:36,919 - freqtrade.optimize - INFO - Download the pair: "BTC_XRP", Interval: 5 min
Traceback (most recent call last):
  File "main.py", line 490, in <module>
    main()
  File "main.py", line 430, in main
    args.func(args)
  File "c:\users\rohit.metro-rohit\desktop\freqtrade-develop\freqtrade\optimize\backtesting.py", line 165, in start
    refresh_pairs=args.refresh_pairs)
  File "c:\users\rohit.metro-rohit\desktop\freqtrade-develop\freqtrade\optimize\__init__.py", line 57, in load_data
    download_backtesting_testdata(datadir, pair=pair, interval=ticker_interval)
  File "c:\users\rohit.metro-rohit\desktop\freqtrade-develop\freqtrade\optimize\__init__.py", line 130, in download_backtesting_testdata
    with open(filename, "wt") as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'freqtrade/tests/testdata\\BTC_XRP-5.json'

**Comment by shusso** [comment]
Thanks for the issue @rohit366 👍 
Can you check does this branch work: https://github.com/gcarq/freqtrade/tree/fix/testdata-path

I don't have windows at hand, so cannot test it out. If it works, I'll create a PR and fix it

**Comment by rohit366** [comment]
@shusso I found out that it was due to error in the json file for XRP, to solve this I removed all the files inside testdats then ran the download_backtest_data to collect all the data again, that fixed the issue.

**Comment by rohit366** [comment]
@shusso after downloading the latest dev zip to my system and running in normally without any changes to files or testdata folder I got this error.

(.env) C:\Users\DeathStar\Desktop\freqtrade-develop\freqtrade>python main.py backtesting --realistic-simulation
2018-01-11 21:30:49,919 - freqtrade.optimize.backtesting - INFO - Using config: config.json ...
Traceback (most recent call last):
  File "main.py", line 472, in <module>
    main()
  File "main.py", line 412, in main
    args.func(args)
  File "c:\users\deathstar\desktop\freqtrade-develop\freqtrade\optimize\backtesting.py", line 152, in start
    config = misc.load_config(args.config)
  File "c:\users\deathstar\desktop\freqtrade-develop\freqtrade\misc.py", line 54, in load_config
    conf = json.load(file)
  File "C:\Users\DeathStar\AppData\Local\Programs\Python\Python36-32\lib\json\__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Users\DeathStar\AppData\Local\Programs\Python\Python36-32\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\DeathStar\AppData\Local\Programs\Python\Python36-32\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\DeathStar\AppData\Local\Programs\Python\Python36-32\lib\json\decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 230 column 65 (char 4722)

**Comment by rohit366** [comment]
I have tried everything but with no success here is the error on my cms window.

(.env) C:\Users\DeathStar\Desktop\freqtrade-develop\freqtrade>python main.py backtesting --realistic-simulation
2018-01-11 23:48:13,450 - freqtrade.optimize.backtesting - INFO - Using config: config.json ...
2018-01-11 23:48:13,454 - freqtrade.misc - INFO - Validating configuration ...
2018-01-11 23:48:13,464 - freqtrade.optimize.backtesting - INFO - Using ticker_interval: 5 ...
2018-01-11 23:48:13,468 - freqtrade.optimize.backtesting - INFO - Using local backtesting data (using whitelist in given config) ...
2018-01-11 23:48:13,473 - freqtrade.optimize - INFO - Download the pair: "BTC_XRP", Interval: 5 min
Traceback (most recent call last):
  File "main.py", line 472, in <module>
    main()
  File "main.py", line 412, in main
    args.func(args)
  File "c:\users\deathstar\desktop\freqtrade-develop\freqtrade\optimize\backtesting.py", line 165, in start
    refresh_pairs=args.refresh_pairs)
  File "c:\users\deathstar\desktop\freqtrade-develop\freqtrade\optimize\__init__.py", line 57, in load_data
    download_backtesting_testdata(datadir, pair=pair, interval=ticker_interval)
  File "c:\users\deathstar\desktop\freqtrade-develop\freqtrade\optimize\__init__.py", line 130, in download_backtesting_testdata
    with open(filename, "wt") as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'freqtrade\\tests\\testdata\\BTC_XRP-5.json'
