### ISSUE TITLE
plot_dataframe.py broken

### ISSUE THREAD

**Issue by glonlas** [gcarq/freqtrade#363]
## Step 2: Describe your environment

  * Python Version: 3.6.3 (`python -V`)
  * Branch: Develop
  * Last Commit ID: 3a902289f11e8d30fa747ee34e40a159333d4ab2 (`git log --format="%H" -n 1`)
 
## Step 3: Describe the problem:
`python3 scripts/plot_dataframe.py --pair ETH` does not work. It raises the error `TypeError: common_args_parser() takes 1 positional argument but 2 were given`

### Steps to reproduce:

  1. run `python3  scripts/plot_dataframe.py --pair ETH`
  2. show the issue
  

### Relevant code exceptions or logs:

  ```
$ python3  scripts/plot_dataframe.py --pair ETH
Traceback (most recent call last):
  File "scripts/plot_dataframe.py", line 69, in <module>
    args = plot_parse_args(sys.argv[1:])
  File "scripts/plot_dataframe.py", line 13, in plot_parse_args
    parser = common_args_parser(args, 'Graph utility')
TypeError: common_args_parser() takes 1 positional argument but 2 were given
  ```

**Comment by glonlas** [comment]
Fixed
