### ISSUE TITLE
forcesell exception

### ISSUE THREAD

**Issue by robmoggach** [gcarq/freqtrade#371]
Executing `/forcesell 56` with `56` being an arbitrary trade from the listed IDs results in an exception being thrown and the bot crashing.

>    MyFreqTradeBot, [Jan 12, 2018 at 9:52:25 AM]:
>    Status: Got OperationalException:

    Traceback (most recent call last):
      File "/home/freqtrade/freqtrade/freqtrade/main.py", line 104, in _process
        check_handle_timedout(_CONF['unfilledtimeout'])
      File "/home/freqtrade/freqtrade/freqtrade/main.py", line 132, in check_handle_timedout
        order = exchange.get_order(trade.open_order_id)
      File "/home/freqtrade/freqtrade/freqtrade/exchange/__init__.py", line 161, in get_order
        return _API.get_order(order_id)
      File "/home/freqtrade/freqtrade/freqtrade/exchange/bittrex.py", line 178, in get_order
        order_id=order_id))
    freqtrade.OperationalException: UUID_INVALID params=(None)

> Issue /start if you think it is safe to restart.

>    MyFreqTradeBot, [Jan 12, 2018 at 9:52:26 AM]:
>    Status: stopped

**Comment by aaur0** [comment]
+1. I am seeing this also.

**Comment by glonlas** [comment]
I reproduced it. We will fix it.

**Comment by glonlas** [comment]
The issue is generated `main.check_handle_timedout()`, my guess is the new trade timeout system hit a trade that just got sold on Bittrex, but where the DB is not up-to-date.

My dirty fix is to try catch `exchange.cancel_order(trade.open_order_id)`on line 138 in `main.py`. But I think there is a better solution.

Attached the patch. If someone wants to look at it.

[0001-Try-Catch-the-exception-raised-when-trade-timeout-fa.patch.txt](https://github.com/gcarq/freqtrade/files/1628132/0001-Try-Catch-the-exception-raised-when-trade-timeout-fa.patch.txt)

**Comment by shusso** [comment]
please re-open if problem still persists 👍
