### ISSUE TITLE
Bot crash when trying to get bid, ask on crappy data

### ISSUE THREAD

**Issue by dtb11288** [gcarq/freqtrade#406]
## Step 1: Have you search for this issue before posting it?

Yes

## Step 2: Describe your environment

  * Python Version: 3.6
  * Branch: Develop
  * Last Commit ID: a4b8db38cae486c3c8d32de332aded836ba99e35
 
## Step 3: Describe the problem:
*Bot crashed*

### Steps to reproduce:

  1. On a start (or re-run) the bot
  
### Observed Results:

  * Crash!
  * Should ignore crap data

### Relevant code exceptions or logs:

  ```
2018-01-19 04:07:38,218 - freqtrade - ERROR - Got fatal exception!
Traceback (most recent call last):
  File "/home/binh/freqtrade/freqtrade/main.py", line 474, in main
    nb_assets=args.dynamic_whitelist,
  File "/home/binh/freqtrade/freqtrade/misc.py", line 82, in throttle
    result = func(*args, **kwargs)
  File "/home/binh/freqtrade/freqtrade/main.py", line 100, in _process
    state_changed = handle_trade(trade) or state_changed
  File "/home/binh/freqtrade/freqtrade/main.py", line 262, in handle_trade
    current_rate = exchange.get_ticker(trade.pair)['bid']
  File "/home/binh/freqtrade/freqtrade/exchange/__init__.py", line 138, in get_ticker
    return _API.get_ticker(pair, refresh)
  File "/home/binh/freqtrade/freqtrade/exchange/bittrex.py", line 133, in get_ticker
    'bid': float(data['result']['Bid']),
TypeError: float() argument must be a string or a number, not 'NoneType'
  ```
### This is the data that I print out:

```
2018-01-19 05:49:26,393 - freqtrade.exchange.bittrex - INFO - {'success': True, 'message': '', 'result': {'Bid': None, 'Ask': None, 'Last': None}}
```

**Comment by shusso** [comment]
should be fixed now in develop 👍
