### ISSUE TITLE
Bot stop when not enough buy amount

### ISSUE THREAD

**Issue by dtb11288** [gcarq/freqtrade#407]
## Step 1: Have you search for this issue before posting it?

Yes

## Step 2: Describe your environment

  * Python Version: 3.6
  * Branch: Develop
  * Last Commit ID: a4b8db38cae486c3c8d32de332aded836ba99e35
 
## Step 3: Describe the problem:
*Bot crashed*

### Steps to reproduce:

  1. On a start (or re-run) the bot
  
### Observed Results:

  * Bot stop!
  * Should not stop in some normally error

### Relevant code exceptions or logs:

  ```
Traceback (most recent call last):
  File "/home/binh/freqtrade/freqtrade/main.py", line 82, in _process
    state_changed = create_trade(float(_CONF['stake_amount']))
  File "/home/binh/freqtrade/freqtrade/main.py", line 337, in create_trade
    order_id = exchange.buy(pair, buy_limit, amount)
  File "/home/binh/freqtrade/freqtrade/exchange/__init__.py", line 102, in buy
    return _API.buy(pair, rate, amount)
  File "/home/binh/freqtrade/freqtrade/exchange/bittrex.py", line 87, in buy
    amount=amount))
freqtrade.OperationalException: INSUFFICIENT_FUNDS params=(BTC_ETH, 0.09057099, 0.007728744049281122)
  ```

**Comment by ElanHasson** [comment]
I'm getting a similar exception:

```
Status: Got OperationalException:
Traceback (most recent call last):
 File "/freqtrade/freqtrade/main.py", line 118, in _process
   state_changed = process_maybe_execute_buy(_CONF, interval)
 File "/freqtrade/freqtrade/main.py", line 65, in process_maybe_execute_buy
   if create_trade(float(_CONF['stake_amount']), interval):
 File "/freqtrade/freqtrade/main.py", line 393, in create_trade
   order_id = exchange.buy(pair, buy_limit, amount)
 File "/freqtrade/freqtrade/exchange/__init__.py", line 102, in buy
   return _API.buy(pair, rate, amount)
 File "/freqtrade/freqtrade/exchange/bittrex.py", line 87, in buy
   amount=amount))
freqtrade.OperationalException: INSUFFICIENT_FUNDS params=(BTC_SC, 3.84e-06, 260.4166666666667)
```

**Comment by othaner** [comment]
I've just got similar except:

`OperationalException:
Traceback (most recent call last):
  File "/freqtrade/freqtrade/freqtradebot.py", line 165, in _process
    state_changed |= self.process_maybe_execute_sell(trade)
  File "/freqtrade/freqtrade/freqtradebot.py", line 359, in process_maybe_execute_sell
    return self.handle_trade(trade)
  File "/freqtrade/freqtrade/freqtradebot.py", line 379, in handle_trade
    self.execute_sell(trade, current_rate)
  File "/freqtrade/freqtrade/freqtradebot.py", line 471, in execute_sell
    order_id = exchange.sell(str(trade.pair), limit, trade.amount)
  File "/freqtrade/freqtrade/exchange/__init__.py", line 120, in sell
    return _API.sell(pair, rate, amount)
  File "/freqtrade/freqtrade/exchange/bittrex.py", line 81, in sell
    amount=amount))
freqtrade.OperationalException: INSUFFICIENT_FUNDS params=(BTC_STEEM, 0.00036418, 1.4236902)`

And it turns out that in Bittrex it was actually made the sell. Now I have an order hang out. I think next time that bot triggers sell signal it will crash again.

**Comment by othaner** [comment]
I did change in database `is_open` to `0`, and add `'INSUFFICIENT_FUNDS'`to bittrex.py

```
temp_error_messages = [
            'NO_API_RESPONSE',
            'MIN_TRADE_REQUIREMENT_NOT_MET',
            'INSUFFICIENT_FUNDS',
        ]
```

**Comment by berlinguyinca** [comment]
I think I fixed this in my fork. I make a PR

**Comment by shusso** [comment]
please re-open if problem still persists 👍
