### ISSUE TITLE
Hyperopt using mongo throwing exception

### ISSUE THREAD

**Issue by aaur0** [gcarq/freqtrade#418]
## Step 1: Have you search for this issue before posting it?

Yes

## Step 2: Describe your environment

  * Python Version: Python 3.6.3 :: Anaconda custom (64-bit)
  * Branch: Develop
  * Last Commit ID: f6df701b84d70f8091c0a025df2bcd20ce8f4a7e
 
## Step 3: Describe the problem:

Running hyperopt using mongodb throws error.

### Steps to reproduce:

  1. activate python env
  2. start mongodb
  3. start mongo worker
  4. Run hyperopt [python freqtrade/main.py -c config_hyperopt.json hyperopt --use-mon
godb]
  
### Observed Results:

  * What happened?
     got an exception in the worker script and it gets killed eventually.

  * What did you expect to happen?
     hyperopt should have run with errors.
### Relevant code exceptions or logs:

  ```
  
Traceback (most recent call last):
  File "/home/batao/anaconda3/envs/py3k/bin/hyperopt-mongo-worker", line 6, in <module>
    sys.exit(hyperopt.mongoexp.main_worker())
  File "/home/batao/anaconda3/envs/py3k/lib/python3.6/site-packages/hyperopt/mongoexp.py", line 1302,
 in main_worker
    return main_worker_helper(options, args)
  File "/home/batao/anaconda3/envs/py3k/lib/python3.6/site-packages/hyperopt/mongoexp.py", line 1249,
 in main_worker_helper
    mworker.run_one(reserve_timeout=float(options.reserve_timeout))
  File "/home/batao/anaconda3/envs/py3k/lib/python3.6/site-packages/hyperopt/mongoexp.py", line 1074,
 in run_one
    result = worker_fn(spec, ctrl)
  File "/home/batao/anaconda3/envs/py3k/lib/python3.6/site-packages/hyperopt/base.py", line 840, in e
valuate
    rval = self.fn(pyll_rval)
  File "/home/batao/freqtrade/freqtrade/optimize/hyperopt.py", line 169, in optimizer
    'stoploss': params['stoploss']})
  File "/home/batao/freqtrade/freqtrade/optimize/backtesting.py", line 126, in backtest
    for pair, pair_data in processed.items():
AttributeError: 'NoneType' object has no attribute 'items'
INFO:hyperopt.mongoexp:exiting with N=9223372036854775803 after 4 consecutive exceptions

  ```

**Comment by aaur0** [comment]
I am not sure if it has to do with my dev environment or its an actual bug in the code? Can you anyone else confirm this, please?

**Comment by shusso** [comment]
feel free to re-open if problem persist.
