### ISSUE TITLE
KeyError thrown when using custom strategy with 3 Moving Averages

### ISSUE THREAD

**Issue by cofibit** [gcarq/freqtrade#522]
* Python Version: 3.6.4
  * Branch: Develop
 
# Issue Description:

KeyError when using custom strategy. The custom strategy uses 10, 20 and 50 moving averages.

### Steps to reproduce:

Create a custom strategy with the following defined indicators:

        macd = ta.MACD(dataframe)
        dataframe['macd'] = macd['macd']
        dataframe['macdsignal'] = macd['macdsignal']
        dataframe['macdhist'] = macd['macdhist']

        dataframe['sma10'] = ta.SMA(dataframe, timeperiod=10)
        dataframe['sma20'] = ta.SMA(dataframe, timeperiod=20)
        dataframe['sma50'] = ta.SMA(dataframe, timeperiod=50)

under populate_buy_trend method define the buy strategy:

        dataframe.loc[
            (
                (dataframe['close'] > dataframe['sma10']) &
                (dataframe['sma10'] > dataframe['sma20']) &
                (dataframe['macd'] > dataframe['macdsignal'])
            ),
            'buy'] = 1

        return dataframe
  
### Observed Results:

Freqtrade produces this error:

2018-02-19 08:48:34,095 - freqtrade.analyze - ERROR - Unexpected error when analyzing ticker for pair BTC_BCC: 'sma10'

### Relevant code exceptions or logs:

File "pandas/_libs/hashtable_class_helper.pxi", line 1273, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'sma10'
2018-02-19 08:48:34,095 - freqtrade.analyze - ERROR - Unexpected error when analyzing ticker for pair BTC_BCC: 'sma10'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2525, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 117, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 139, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1265, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1273, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'sma10'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/freqtrade.0.16/freqtrade/analyze.py", line 99, in get_signal
    dataframe = analyze_ticker(ticker_hist)
  File "/home/pi/freqtrade.0.16/freqtrade/analyze.py", line 80, in analyze_ticker
    dataframe = populate_buy_trend(dataframe)
  File "/home/pi/freqtrade.0.16/freqtrade/analyze.py", line 59, in populate_buy_trend
    return strategy.populate_buy_trend(dataframe=dataframe)
  File "/home/pi/freqtrade.0.16/freqtrade/strategy/strategy.py", line 172, in populate_buy_trend
    return self.custom_strategy.populate_buy_trend(dataframe)
  File "/home/pi/freqtrade.0.16/user_data/strategies/momo.py", line 232, in populate_buy_trend
    'buy'] = 1
  File "/usr/local/lib/python3.6/site-packages/pandas/core/frame.py", line 2139, in __getitem__
    return self._getitem_column(key)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/frame.py", line 2146, in _getitem_column
    return self._get_item_cache(key)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/generic.py", line 1842, in _get_item_cache
    values = self._data.get(item)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/internals.py", line 3843, in get
    loc = self.items.get_loc(item)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2527, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 117, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 139, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1265, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1273, in pandas._libs.hashtable.PyObjectHashTable.get_item

**Comment by stephendade** [comment]
I've just tried this with the latest develop and did not encounter the bug. Could you confirm if this is still an issue?

**Comment by jblestang** [comment]
Make sure you provide your strategy file on the command line, else your custom indicators will not be made available

**Comment by cofibit** [comment]
@stephendade I tried it again using the latest develop branch but still got the same error.

**Comment by stephendade** [comment]
I noticed that you're using a Rasberry Pi. Could you try on a PC or laptop? Just wanting to narrow down if the Pi is the issue.

**Comment by cofibit** [comment]
With backtesting command I get the error below. I had attached the strategy file here as well

[script.txt](https://github.com/gcarq/freqtrade/files/1758274/script.txt)

`python3 ./freqtrade/main.py -s momo.py backtesting --realistic-simulation --live
2018-02-26 18:59:57,961 - freqtrade.optimize.backtesting - INFO - Using config: config.json ...
2018-02-26 18:59:57,969 - freqtrade.misc - INFO - Validating configuration ...
2018-02-26 18:59:58,045 - freqtrade.strategy.strategy - INFO - Load strategy class: MomoStrategy (user_data.strategies.momo.py)
2018-02-26 18:59:58,046 - freqtrade.strategy.strategy - INFO - Override strategy 'minimal_roi' with value in config file.
2018-02-26 18:59:58,046 - freqtrade.strategy.strategy - INFO - Override strategy 'stoploss' with value in config file: -0.1.
2018-02-26 18:59:58,053 - freqtrade.strategy.strategy - INFO - Override strategy 'ticker_interval' with value in config file: 1440.
2018-02-26 18:59:58,060 - freqtrade.optimize.backtesting - INFO - Using ticker_interval: 1440 ...
2018-02-26 18:59:58,061 - freqtrade.optimize.backtesting - INFO - Using stake_currency: BTC ...
2018-02-26 18:59:58,061 - freqtrade.optimize.backtesting - INFO - Using stake_amount: 0.002 ...
2018-02-26 18:59:58,062 - freqtrade.optimize.backtesting - INFO - Downloading data for all pairs in whitelist ...
2018-02-26 19:00:12,678 - freqtrade.optimize.backtesting - INFO - Using max_open_trades: 3 ...
2018-02-26 19:00:13,641 - freqtrade.optimize.backtesting - INFO - Measuring data from 2014-03-07T00:00:00+00:00 up to 2018-02-26T00:00:00+00:00 (1452 days)..
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2525, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 117, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 139, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1265, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1273, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'sma10'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./freqtrade/main.py", line 564, in <module>
    main(sys.argv[1:])
  File "./freqtrade/main.py", line 498, in main
    args.func(args)
  File "/home/pi/freqtrade/freqtrade/optimize/backtesting.py", line 226, in start
    'record': args.export
  File "/home/pi/freqtrade/freqtrade/optimize/backtesting.py", line 120, in backtest
    ticker_data = populate_sell_trend(populate_buy_trend(pair_data))[headers]
  File "/home/pi/freqtrade/freqtrade/analyze.py", line 59, in populate_buy_trend
    return strategy.populate_buy_trend(dataframe=dataframe)
  File "/home/pi/freqtrade/freqtrade/strategy/strategy.py", line 172, in populate_buy_trend
    return self.custom_strategy.populate_buy_trend(dataframe)
  File "/home/pi/freqtrade/user_data/strategies/momo.py", line 233, in populate_buy_trend
    'buy'] = 1
  File "/usr/local/lib/python3.6/site-packages/pandas/core/frame.py", line 2139, in __getitem__
    return self._getitem_column(key)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/frame.py", line 2146, in _getitem_column
    return self._get_item_cache(key)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/generic.py", line 1842, in _get_item_cache
    values = self._data.get(item)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/internals.py", line 3843, in get
    loc = self.items.get_loc(item)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2527, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 117, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 139, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1265, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1273, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'sma10'
`

**Comment by jblestang** [comment]
Use « -s momo » not « -s momo.py »

**Comment by cofibit** [comment]
@jblestang yes it was a typo error I meant -s momo.

**Comment by cofibit** [comment]
@stephendade I tried it on macOS Sierra 10.13.3 using anaconda environment with python 3.6.4 but still got the same error :(

`python3.6 ./freqtrade/main.py -s momo backtesting --realistic-simulation --live
2018-02-27 19:03:11,034 - freqtrade.optimize.backtesting - INFO - Using config: config.json ...
2018-02-27 19:03:11,035 - freqtrade.misc - INFO - Validating configuration ...
2018-02-27 19:03:11,042 - freqtrade.strategy.strategy - INFO - Load strategy class: MomoStrategy (user_data.strategies.momo.py)
2018-02-27 19:03:11,042 - freqtrade.strategy.strategy - INFO - Override strategy 'minimal_roi' with value in config file.
2018-02-27 19:03:11,042 - freqtrade.strategy.strategy - INFO - Override strategy 'stoploss' with value in config file: -0.02.
2018-02-27 19:03:11,043 - freqtrade.optimize.backtesting - INFO - Using ticker_interval: 60 ...
2018-02-27 19:03:11,044 - freqtrade.optimize.backtesting - INFO - Using stake_currency: BTC ...
2018-02-27 19:03:11,044 - freqtrade.optimize.backtesting - INFO - Using stake_amount: 0.002 ...
2018-02-27 19:03:11,044 - freqtrade.optimize.backtesting - INFO - Downloading data for all pairs in whitelist ...
2018-02-27 19:03:23,145 - freqtrade.optimize.backtesting - INFO - Using max_open_trades: 3 ...
2018-02-27 19:03:23,241 - freqtrade.optimize.backtesting - INFO - Measuring data from 2017-12-29T12:00:00+00:00 up to 2018-02-27T11:00:00+00:00 (59 days)..
Traceback (most recent call last):
  File "/Users/arvin/anaconda/envs/bot/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2525, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 117, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 139, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1265, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1273, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'sma10'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./freqtrade/main.py", line 564, in <module>
    main(sys.argv[1:])
  File "./freqtrade/main.py", line 498, in main
    args.func(args)
  File "/Users/arvin/dev/bot/freqtrade/freqtrade/optimize/backtesting.py", line 226, in start
    'record': args.export
  File "/Users/arvin/dev/bot/freqtrade/freqtrade/optimize/backtesting.py", line 120, in backtest
    ticker_data = populate_sell_trend(populate_buy_trend(pair_data))[headers]
  File "/Users/arvin/dev/bot/freqtrade/freqtrade/analyze.py", line 59, in populate_buy_trend
    return strategy.populate_buy_trend(dataframe=dataframe)
  File "/Users/arvin/dev/bot/freqtrade/freqtrade/strategy/strategy.py", line 172, in populate_buy_trend
    return self.custom_strategy.populate_buy_trend(dataframe)
  File "/Users/arvin/dev/bot/freqtrade/user_data/strategies/momo.py", line 233, in populate_buy_trend
    'buy'] = 1
  File "/Users/arvin/anaconda/envs/bot/lib/python3.6/site-packages/pandas/core/frame.py", line 2139, in __getitem__
    return self._getitem_column(key)
  File "/Users/arvin/anaconda/envs/bot/lib/python3.6/site-packages/pandas/core/frame.py", line 2146, in _getitem_column
    return self._get_item_cache(key)
  File "/Users/arvin/anaconda/envs/bot/lib/python3.6/site-packages/pandas/core/generic.py", line 1842, in _get_item_cache
    values = self._data.get(item)
  File "/Users/arvin/anaconda/envs/bot/lib/python3.6/site-packages/pandas/core/internals.py", line 3843, in get
    loc = self.items.get_loc(item)
  File "/Users/arvin/anaconda/envs/bot/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2527, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 117, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 139, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1265, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1273, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'sma10'
`

**Comment by stephendade** [comment]
I've just tried your strategy on Win10, Python 3.6.4, latest develop branch.

It all worked fine for me. The only way I could replicate your error message was to comment out the ``dataframe['sma10'] = ta.SMA(dataframe, timeperiod=10)`` line.

Could we get the _exact_ strategy file that you're using?

**Comment by cofibit** [comment]
@stephendade here you go.
[momo.txt](https://github.com/gcarq/freqtrade/files/1762387/momo.txt)

**Comment by stephendade** [comment]
Cool. I took a look at the file and the ema10 and a few other items were commented out. It's not well shown, but the `"""` in Python is the start/end of a multiline comment.

Also found a few other typos/errors. Fixed file attached.

[momo.txt](https://github.com/gcarq/freqtrade/files/1762398/momo.txt)

**Comment by cofibit** [comment]
@stephendade great that worked!! thanks allot.

**Comment by cofibit** [comment]
issue fixed thanks to @stephendade closing this one.
