### ISSUE TITLE
Setting max_open_trades = 0 crashs bot

### ISSUE THREAD

**Issue by baudbox** [gcarq/freqtrade#534]
## Step 1: Have you search for this issue before posting it?
yes and per slack discussion

## Step 2: Describe your environment

  * Python Version: Python 3.6.3
  * Branch: Develop
  * Last Commit ID: 4dca84817eb1b62047a9e4d282254392ea978e44
 
## Step 3: Describe the problem:

Goal: Stop bot to making any new purchases and let the sell on its own old bags/trades

### Steps to reproduce:

  1. Stop the bot
  2. Set max_open_trades = 0
  3. Restart bot
  
### Observed Results:

Bot crashs

### Relevant code exceptions or logs:

  ```
2018-03-03 11:41:03,727 - freqtrade - INFO - Starting freqtrade 0.16.0 (loglevel=DEBUG)
2018-03-03 11:41:03,730 - freqtrade.misc - INFO - Validating configuration ...
2018-03-03 11:41:03,778 - freqtrade.misc - CRITICAL - Invalid configuration. See config.json.example. Reason: 0 is less than the minimum of 1

Failed validating 'minimum' in schema['properties']['max_open_trades']:
    {'minimum': 1, 'type': 'integer'}

On instance['max_open_trades']:
    0
Traceback (most recent call last):
  File "./freqtrade/main.py", line 564, in <module>
    main(sys.argv[1:])
  File "./freqtrade/main.py", line 514, in main
    _CONF = load_config(args.config)
  File "/root/freqtrade/freqtrade/misc.py", line 105, in load_config
    best_match(Draft4Validator(CONF_SCHEMA).iter_errors(conf)).message
jsonschema.exceptions.ValidationError: 0 is less than the minimum of 1
```

**Comment by shusso** [comment]
fixed in develop
