### ISSUE TITLE
AttributeError when trying to use hyperopt with mongodb

### ISSUE THREAD

**Issue by muffetman** [gcarq/freqtrade#552]
## Step 2: Describe your environment

  * Python Version: 3.6.3
  * Branch: Master
  * Last Commit ID: 1bdbe09
  * O/S: CentOS 7.3
  * mongodb-org versions: v3.2.19, v3.4, v3.6
 
## Step 3: Describe the problem:
When executing hyperopt with mongodb I received the following error: `AttributeError: Can't pickle local object 'generate_optimizer.<locals>.optimizer'`

I setup my environment first with mongodb v3.6, then downgraded to v3.4 then finally v3.2 and received the same error. Could this be related to CentOS? I have searched for this error and only found one result relevant to hyperopt, but I don't think it was the same problem. 

### Steps to reproduce:

  1. Start mongodb with `python3 scripts/start-mongodb.py`
  2. Start hyperopt-worker with `python3 scripts/start-hyperopt-worker.py`
  3. Start hyperopt with `python3 ./freqtrade/main.py -c config.json hyperopt --use-mongodb`
  
### Observed Results:

  * What happened? mongodb startup looks ok and listens for connections on port 1234. hyperopt-worker starts up and spams "no job found, sleeping for 0.8s". Can see connections to mongodb now open. Execute startup of hyperopt with --use-mongodb and fails with above error. 

  * What did you expect to happen? Hyperopt on steroids!

### Relevant code exceptions or logs:

 ```
$ python3 scripts/start-mongodb.py
2018-03-13T16:52:16.934+0100 I CONTROL  [initandlisten] MongoDB starting : pid=6647 port=1234 dbpath=/usr/local/freqtrade/scripts/../.hyperopt/mongodb 64-bit host=rocinante
2018-03-13T16:52:16.934+0100 I CONTROL  [initandlisten] db version v3.2.19
2018-03-13T16:52:16.934+0100 I CONTROL  [initandlisten] git version: a9f574de6a566a58b24d126b44a56718d181e989
2018-03-13T16:52:16.934+0100 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.1e-fips 11 Feb 2013
2018-03-13T16:52:16.934+0100 I CONTROL  [initandlisten] allocator: tcmalloc
2018-03-13T16:52:16.934+0100 I CONTROL  [initandlisten] modules: none
2018-03-13T16:52:16.934+0100 I CONTROL  [initandlisten] build environment:
2018-03-13T16:52:16.934+0100 I CONTROL  [initandlisten]     distmod: rhel70
2018-03-13T16:52:16.934+0100 I CONTROL  [initandlisten]     distarch: x86_64
2018-03-13T16:52:16.934+0100 I CONTROL  [initandlisten]     target_arch: x86_64
2018-03-13T16:52:16.934+0100 I CONTROL  [initandlisten] options: { net: { bindIp: "127.0.0.1", port: 1234 }, storage: { dbPath: "/usr/local/freqtrade/scripts/../.hyperopt/mongodb" } }
2018-03-13T16:52:16.993+0100 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=1G,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),checkpoint=(wait=60,log_size=2GB),statistics_log=(wait=0),verbose=(recovery_progress),
2018-03-13T16:52:17.102+0100 I CONTROL  [initandlisten]
2018-03-13T16:52:17.102+0100 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.
2018-03-13T16:52:17.102+0100 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2018-03-13T16:52:17.102+0100 I CONTROL  [initandlisten]
2018-03-13T16:52:17.102+0100 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/defrag is 'always'.
2018-03-13T16:52:17.102+0100 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2018-03-13T16:52:17.102+0100 I CONTROL  [initandlisten]
2018-03-13T16:52:17.125+0100 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/usr/local/freqtrade/scripts/../.hyperopt/mongodb/diagnostic.data'
2018-03-13T16:52:17.125+0100 I NETWORK  [HostnameCanonicalizationWorker] Starting hostname canonicalization worker
2018-03-13T16:52:17.125+0100 I NETWORK  [initandlisten] waiting for connections on port 1234
2018-03-13T16:52:59.833+0100 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:54674 #1 (1 connection now open)
2018-03-13T16:52:59.838+0100 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:54676 #2 (2 connections now open)
2018-03-13T16:55:00.191+0100 I NETWORK  [conn1] end connection 127.0.0.1:54674 (1 connection now open)
2018-03-13T16:55:00.192+0100 I NETWORK  [conn2] end connection 127.0.0.1:54676 (0 connections now open)
2018-03-13T16:55:01.578+0100 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:54678 #3 (1 connection now open)
2018-03-13T16:55:01.583+0100 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:54680 #4 (2 connections now open)
 ```

 ```
$ python3 scripts/start-hyperopt-worker.py
INFO:hyperopt.mongoexp:PROTOCOL mongo
INFO:hyperopt.mongoexp:USERNAME None
INFO:hyperopt.mongoexp:HOSTNAME 127.0.0.1
INFO:hyperopt.mongoexp:PORT 1234
INFO:hyperopt.mongoexp:PATH /freqtrade_hyperopt/jobs
INFO:hyperopt.mongoexp:DB freqtrade_hyperopt
INFO:hyperopt.mongoexp:COLLECTION jobs
INFO:hyperopt.mongoexp:PASS None
INFO:hyperopt.mongoexp:no job found, sleeping for 0.1s
INFO:hyperopt.mongoexp:no job found, sleeping for 0.3s
INFO:hyperopt.mongoexp:no job found, sleeping for 0.3s
INFO:hyperopt.mongoexp:no job found, sleeping for 0.6s
 ```

  ```
 $ python3 ./freqtrade/main.py -c config.json hyperopt --use-mongodb

Using config: config.json ...

Validating configuration ...

Load strategy class: DefaultStrategy (.default_strategy.py)

Using mongodb ...

Start scripts/start-mongodb.sh and start-hyperopt-worker.sh manually!
Traceback (most recent call last):
  File "./freqtrade/main.py", line 564, in <module>
    main(sys.argv[1:])
  File "./freqtrade/main.py", line 498, in main
    args.func(args)
  File "/usr/local/freqtrade/freqtrade/optimize/hyperopt.py", line 528, in start
    trials=TRIALS
  File "/usr/local/freqtrade/.env/lib64/python3.6/site-packages/hyperopt/fmin.py", line 307, in fmin
    return_argmin=return_argmin,
  File "/usr/local/freqtrade/.env/lib64/python3.6/site-packages/hyperopt/base.py", line 635, in fmin
    return_argmin=return_argmin)
  File "/usr/local/freqtrade/.env/lib64/python3.6/site-packages/hyperopt/fmin.py", line 318, in fmin
    verbose=verbose)
  File "/usr/local/freqtrade/.env/lib64/python3.6/site-packages/hyperopt/fmin.py", line 77, in __init__
    domain, protocol=self.pickle_protocol)
AttributeError: Can't pickle local object 'generate_optimizer.<locals>.optimizer'
  ```

**Comment by gcarq** [comment]
Hi, thanks for reporting this.
It's not related to CentOS or mongodb, I'm able to reproduce it on Arch Linux. This bug got introduced with bf72b5bc37c4b3d9be4b86ee8e452226c369cfcd. It's because hyperopt needs to load the `optimizer()` within `scripts/start-hyperopt-worker.py`, but hyperopt has some limitations and requires `optimizer()` on module level, AFAIK it can't handle inner functions as optimizer.

**Comment by lacvapps** [comment]
This bug is fixed by the latest merge into dev. There is a new issue now #568
