### ISSUE TITLE
Value Error

### ISSUE THREAD

**Issue by ElBibino** [gcarq/freqtrade#6]
Hi,
I have this problem.

How i can resolve this ?

2017-09-01 18:39:26,956 - main - INFO - Creating new trade with stake_amount: 0.002000 ...
2017-09-01 18:39:29,536 - analyze - DEBUG - buy_trigger: 2017-09-01T16:37:00 (pair=BTC_OMG, signal=False)
2017-09-01 18:39:29,536 - main - ERROR - ValueError during trade creation
Traceback (most recent call last):
  File "/home/startup/Bureau/freqtrade-master/main.py", line 86, in _process
    Session.add(create_trade(float(CONFIG['stake_amount']), api_wrapper.exchange))
  File "/home/startup/Bureau/freqtrade-master/main.py", line 205, in create_trade
    raise ValueError('No buy signal from pairs: {}'.format(', '.join(whitelist)))

**Comment by gcarq** [comment]
This is not a problem. It works as expected, each time before a buy order is placed the trading indicator gets checked and if none of the specified pairs triggers in this iteration you get this ValueError. The logging is just messy because the code is in a early state, I will push a fix that will omit this message

**Comment by ElBibino** [comment]
Ok thank you :) 
it's just looping on it for an hour: /

...
2017-09-01 21:00:56,555 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): bittrex.com
2017-09-01 21:00:56,872 - urllib3.connectionpool - DEBUG - https://bittrex.com:443 "GET /api/v1.1/public/getmarkets HTTP/1.1" 200 8346
2017-09-01 21:00:56,882 - utils - INFO - Config is valid ...
2017-09-01 21:00:57,346 - __main__ - INFO - Starting freqtrade 0.8.0
2017-09-01 21:00:57,348 - JobQueue - DEBUG - JobQueue thread started
2017-09-01 21:00:57,350 - rpc.telegram - INFO - TelegramHandler is listening for following commands: [['status'], ['profit'], ['start'], ['stop'], ['forcesell'], ['performance']]
2017-09-01 21:01:02,123 - rpc.telegram - INFO - Executing handler: _start for chat_id: 439610149
2017-09-01 21:01:02,131 - main - DEBUG - Creating TradeThread instance
2017-09-01 21:01:02,131 - main - INFO - Trader started
2017-09-01 21:01:02,136 - main - INFO - Creating new trade with stake_amount: 0.002495 ...
/usr/local/lib/python3.5/dist-packages/pandas/core/indexing.py:179: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)
2017-09-01 21:01:07,473 - analyze - DEBUG - buy_trigger: 2017-09-01T18:58:00 (pair=BTC_OMG, signal=False)
2017-09-01 21:01:07,473 - main - ERROR - ValueError during trade creation
Traceback (most recent call last):
  File "/home/startup/Bureau/freqtrade-master/main.py", line 86, in _process
    Session.add(create_trade(float(CONFIG['stake_amount']), api_wrapper.exchange))
  File "/home/startup/Bureau/freqtrade-master/main.py", line 205, in create_trade
    raise ValueError('No buy signal from pairs: {}'.format(', '.join(whitelist)))
ValueError: No buy signal from pairs: BTC_OMG
2017-09-01 21:01:32,491 - main - INFO - Creating new trade with stake_amount: 0.002495 ...
2017-09-01 21:01:35,254 - analyze - DEBUG - buy_trigger: 2017-09-01T18:58:00 (pair=BTC_OMG, signal=False)
2017-09-01 21:01:35,254 - main - ERROR - ValueError during trade creation
Traceback (most recent call last):
  File "/home/startup/Bureau/freqtrade-master/main.py", line 86, in _process
    Session.add(create_trade(float(CONFIG['stake_amount']), api_wrapper.exchange))
  File "/home/startup/Bureau/freqtrade-master/main.py", line 205, in create_trade
    raise ValueError('No buy signal from pairs: {}'.format(', '.join(whitelist)))
ValueError: No buy signal from pairs: BTC_OMG
2017-09-01 21:02:00,261 - main - INFO - Creating new trade with stake_amount: 0.002495 ...
2017-09-01 21:02:04,467 - analyze - DEBUG - buy_trigger: 2017-09-01T18:58:00 (pair=BTC_OMG, signal=False)
2017-09-01 21:02:04,467 - main - ERROR - ValueError during trade creation
Traceback (most recent call last):
  File "/home/startup/Bureau/freqtrade-master/main.py", line 86, in _process
    Session.add(create_trade(float(CONFIG['stake_amount']), api_wrapper.exchange))
  File "/home/startup/Bureau/freqtrade-master/main.py", line 205, in create_trade
    raise ValueError('No buy signal from pairs: {}'.format(', '.join(whitelist)))
ValueError: No buy signal from pairs: BTC_OMG
2017-09-01 21:02:29,471 - main - INFO - Creating new trade with stake_amount: 0.002495 ...
2017-09-01 21:02:36,436 - analyze - DEBUG - buy_trigger: 2017-09-01T19:00:00 (pair=BTC_OMG, signal=False)
2017-09-01 21:02:36,437 - main - ERROR - ValueError during trade creation
Traceback (most recent call last):
  File "/home/startup/Bureau/freqtrade-master/main.py", line 86, in _process
    Session.add(create_trade(float(CONFIG['stake_amount']), api_wrapper.exchange))
  File "/home/startup/Bureau/freqtrade-master/main.py", line 205, in create_trade
    raise ValueError('No buy signal from pairs: {}'.format(', '.join(whitelist)))
ValueError: No buy signal from pairs: BTC_OMG
2017-09-01 21:03:01,442 - main - INFO - Creating new trade with stake_amount: 0.002495 ...
2017-09-01 21:03:04,071 - analyze - DEBUG - buy_trigger: 2017-09-01T19:00:00 (pair=BTC_OMG, signal=False)
2017-09-01 21:03:04,072 - main - ERROR - ValueError during trade creation
Traceback (most recent call last):
  File "/home/startup/Bureau/freqtrade-master/main.py", line 86, in _process
    Session.add(create_trade(float(CONFIG['stake_amount']), api_wrapper.exchange))
  File "/home/startup/Bureau/freqtrade-master/main.py", line 205, in create_trade
    raise ValueError('No buy signal from pairs: {}'.format(', '.join(whitelist)))
ValueError: No buy signal from pairs: BTC_OMG
2017-09-01 21:03:29,092 - main - INFO - Creating new trade with stake_amount: 0.002495 ...
2017-09-01 21:03:31,747 - analyze - DEBUG - buy_trigger: 2017-09-01T19:00:00 (pair=BTC_OMG, signal=False)
2017-09-01 21:03:31,747 - main - ERROR - ValueError during trade creation
Traceback (most recent call last):
  File "/home/startup/Bureau/freqtrade-master/main.py", line 86, in _process
    Session.add(create_trade(float(CONFIG['stake_amount']), api_wrapper.exchange))
  File "/home/startup/Bureau/freqtrade-master/main.py", line 205, in create_trade
    raise ValueError('No buy signal from pairs: {}'.format(', '.join(whitelist)))
ValueError: No buy signal from pairs: BTC_OMG
2017-09-01 21:03:56,751 - main - INFO - Creating new trade with stake_amount: 0.002495 ...
2017-09-01 21:04:00,403 - analyze - DEBUG - buy_trigger: 2017-09-01T19:00:00 (pair=BTC_OMG, signal=False)
2017-09-01 21:04:00,403 - main - ERROR - ValueError during trade creation
Traceback (most recent call last):
  File "/home/startup/Bureau/freqtrade-master/main.py", line 86, in _process
    Session.add(create_trade(float(CONFIG['stake_amount']), api_wrapper.exchange))
  File "/home/startup/Bureau/freqtrade-master/main.py", line 205, in create_trade
    raise ValueError('No buy signal from pairs: {}'.format(', '.join(whitelist)))
ValueError: No buy signal from pairs: BTC_OMG
2017-09-01 21:04:25,428 - main - INFO - Creating new trade with stake_amount: 0.002495 ...
2017-09-01 21:04:29,493 - analyze - DEBUG - buy_trigger: 2017-09-01T19:02:00 (pair=BTC_OMG, signal=False)
2017-09-01 21:04:29,493 - main - ERROR - ValueError during trade creation
Traceback (most recent call last):
  File "/home/startup/Bureau/freqtrade-master/main.py", line 86, in _process
    Session.add(create_trade(float(CONFIG['stake_amount']), api_wrapper.exchange))
  File "/home/startup/Bureau/freqtrade-master/main.py", line 205, in create_trade
    raise ValueError('No buy signal from pairs: {}'.format(', '.join(whitelist)))
ValueError: No buy signal from pairs: BTC_OMG
2017-09-01 21:04:54,519 - main - INFO - Creating new trade with stake_amount: 0.002495 ...
2017-09-01 21:04:57,044 - analyze - DEBUG - buy_trigger: 2017-09-01T19:02:00 (pair=BTC_OMG, signal=False)
2017-09-01 21:04:57,044 - main - ERROR - ValueError during trade creation
Traceback (most recent call last):
  File "/home/startup/Bureau/freqtrade-master/main.py", line 86, in _process
    Session.add(create_trade(float(CONFIG['stake_amount']), api_wrapper.exchange))
  File "/home/startup/Bureau/freqtrade-master/main.py", line 205, in create_trade
    raise ValueError('No buy signal from pairs: {}'.format(', '.join(whitelist)))
ValueError: No buy signal from pairs: BTC_OMG
2017-09-01 21:05:22,069 - main - INFO - Creating new trade with stake_amount: 0.002495 ...
2017-09-01 21:05:24,648 - analyze - DEBUG - buy_trigger: 2017-09-01T19:02:00 (pair=BTC_OMG, signal=False)
2017-09-01 21:05:24,648 - main - ERROR - ValueError during trade creation
Traceback (most recent call last):
  File "/home/startup/Bureau/freqtrade-master/main.py", line 86, in _process
    Session.add(create_trade(float(CONFIG['stake_amount']), api_wrapper.exchange))
  File "/home/startup/Bureau/freqtrade-master/main.py", line 205, in create_trade
    raise ValueError('No buy signal from pairs: {}'.format(', '.join(whitelist)))
ValueError: No buy signal from pairs: BTC_OMG
2017-09-01 21:05:49,669 - main - INFO - Creating new trade with stake_amount: 0.002495 ...
2017-09-01 21:05:52,493 - analyze - DEBUG - buy_trigger: 2017-09-01T19:02:00 (pair=BTC_OMG, signal=False)
2017-09-01 21:05:52,493 - main - ERROR - ValueError during trade creation
Traceback (most recent call last):
  File "/home/startup/Bureau/freqtrade-master/main.py", line 86, in _process
    Session.add(create_trade(float(CONFIG['stake_amount']), api_wrapper.exchange))
  File "/home/startup/Bureau/freqtrade-master/main.py", line 205, in create_trade
    raise ValueError('No buy signal from pairs: {}'.format(', '.join(whitelist)))
ValueError: No buy signal from pairs: BTC_OMG
2017-09-01 21:06:17,519 - main - INFO - Creating new trade with stake_amount: 0.002495 ...
2017-09-01 21:06:20,052 - analyze - DEBUG - buy_trigger: 2017-09-01T19:04:00 (pair=BTC_OMG, signal=False)
2017-09-01 21:06:20,053 - main - ERROR - ValueError during trade creation
Traceback (most recent call last):
  File "/home/startup/Bureau/freqtrade-master/main.py", line 86, in _process
    Session.add(create_trade(float(CONFIG['stake_amount']), api_wrapper.exchange))
  File "/home/startup/Bureau/freqtrade-master/main.py", line 205, in create_trade
    raise ValueError('No buy signal from pairs: {}'.format(', '.join(whitelist)))
ValueError: No buy signal from pairs: BTC_OMG
2017-09-01 21:06:45,078 - main - INFO - Creating new trade with stake_amount: 0.002495 ...
2017-09-01 21:06:47,578 - analyze - DEBUG - buy_trigger: 2017-09-01T19:04:00 (pair=BTC_OMG, signal=False)
2017-09-01 21:06:47,578 - main - ERROR - ValueError during trade creation
Traceback (most recent call last):
  File "/home/startup/Bureau/freqtrade-master/main.py", line 86, in _process
    Session.add(create_trade(float(CONFIG['stake_amount']), api_wrapper.exchange))
  File "/home/startup/Bureau/freqtrade-master/main.py", line 205, in create_trade
    raise ValueError('No buy signal from pairs: {}'.format(', '.join(whitelist)))
ValueError: No buy signal from pairs: BTC_OMG
2017-09-01 21:07:12,594 - main - INFO - Creating new trade with stake_amount: 0.002495 ...
2017-09-01 21:07:15,069 - analyze - DEBUG - buy_trigger: 2017-09-01T19:04:00 (pair=BTC_OMG, signal=False)
2017-09-01 21:07:15,069 - main - ERROR - ValueError during trade creation
Traceback (most recent call last):
  File "/home/startup/Bureau/freqtrade-master/main.py", line 86, in _process
    Session.add(create_trade(float(CONFIG['stake_amount']), api_wrapper.exchange))
  File "/home/startup/Bureau/freqtrade-master/main.py", line 205, in create_trade
    raise ValueError('No buy signal from pairs: {}'.format(', '.join(whitelist)))
ValueError: No buy signal from pairs: BTC_OMG
...

I wait new push with impatience :)

Bye

**Comment by gcarq** [comment]
It has been pushed to `master` branch already (https://github.com/gcarq/freqtrade/commit/99cbf72dc42f19c3e93e05f342cf5232a255150d), did you pull or download the code again?

As far as I can see you only specified `BTC_OMG` in `pair_whitelist`. This can take a while, it depends on the current volume because you only get a buy_signal if the price changes over a certain threshold. I usually have around 10 pairs with somewhat of a 24h volume in my list.

**Comment by gcarq** [comment]
Is this issue stil relevant?

**Comment by shusso** [comment]
@gcarq at least I haven't noticed this problem anymore with the latest `master`
