### ISSUE TITLE
jsonschema.exceptions.ValidationError: 'BNB' is not one of ['BTC', 'ETH', 'USDT']

### ISSUE THREAD

**Issue by xFFFFF** [gcarq/freqtrade#616]
I would like to trade on BNB couples. I changed what I need in config.json. I added BNB to fiat_convert.py. Branch objectify-ccxt. When I run freqtrade, this error pops up:

```
2018-04-21 14:27:11,669 - root - INFO - Generating grammar tables from /usr/lib/python3.6/lib2to3/Grammar.txt
2018-04-21 14:27:11,741 - root - INFO - Generating grammar tables from /usr/lib/python3.6/lib2to3/PatternGrammar.txt
2018-04-21 14:27:12,055 - freqtrade - INFO - Starting freqtrade 0.16.0 (loglevel=INFO)
2018-04-21 14:27:12,055 - freqtrade.configuration - INFO - Using config: config.json ...
2018-04-21 14:27:12,055 - freqtrade.configuration - INFO - Validating configuration ...
2018-04-21 14:27:12,063 - freqtrade.configuration - CRITICAL - Invalid configuration. See config.json.example. Reason: 'BNB' is not one of ['BTC', 'ETH', 'USDT']

Failed validating 'enum' in schema['properties']['stake_currency']:
    {'enum': ['BTC', 'ETH', 'USDT'], 'type': 'string'}

On instance['stake_currency']:
    'BNB'
2018-04-21 14:27:12,065 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "./freqtrade/main.py", line 49, in main
    freqtrade = FreqtradeBot(configuration.get_config())
  File "/home/f/freqtrade/freqtrade/configuration.py", line 202, in get_config
    self.config = self.load_config()
  File "/home/f/freqtrade/freqtrade/configuration.py", line 34, in load_config
    config = self._load_config_file(self.args.config)
  File "/home/f/freqtrade/freqtrade/configuration.py", line 70, in _load_config_file
    return self._validate_config(conf)
  File "/home/f/freqtrade/freqtrade/configuration.py", line 193, in _validate_config
    best_match(Draft4Validator(Constants.CONF_SCHEMA).iter_errors(conf)).message
jsonschema.exceptions.ValidationError: 'BNB' is not one of ['BTC', 'ETH', 'USDT']
```

I'm starting an adventure with freqtrade. I have not yet been able to run it.

**Comment by xmatthias** [comment]
Currently only BTC, ETH and USDT are supported. There are a few places which need tweaking to get this to work.

Is this on ccxt Branch or develop?
I got a (not yet published) branch for ccxt which fixes bugs related to different stake currencies, so only one location requires a change to support other stakes - but i think there are other issues with CCXT which need attention first.

**Comment by xFFFFF** [comment]
> Branch objectify-ccxt.

I will try with search all files for looking string ETH

**Comment by xmatthias** [comment]
sorry - missed that one.

only changes needed are in `Configuration.py` (and a small fix in `fiat_convert` - as otherwise it errors with unknown stake currency)

**Comment by xmatthias** [comment]
With pr #620 merged to feat/objectify-ccxt, i think this issue can be closed - the only place to modify is [constants.py, line 19](https://github.com/gcarq/freqtrade/blob/develop/freqtrade/constants.py#L19) which defines allowed stake currencies.
