### ISSUE TITLE
[ccxt] All trade data is reseted after bot stopped

### ISSUE THREAD

**Issue by gitlines** [gcarq/freqtrade#633]
## Step 1: Have you search for this issue before posting it?

- I did not find anything

## Step 2: Describe your environment

  * Python Version: 3.65 
  * Branch: CC
  * Last Commit ID: acb1b50924cdd6cdf9df6906dc09b4f81ff0e503
 
## Step 3: Describe the problem:

* after bot stops, a restart via telegram and `/start` command, the trading history is reset.

### Steps to reproduce:

  1. Start bot with Binance on ccxt branch
  2. Wait till it stops due to some error
  3. Restart bot and notice that trade count is set to 0
  
### Observed Results:

  * After the bot stopped due to an error and is restarted, alle statistics are reset
  * Expectation was that stats are kept

### Relevant code exceptions or logs:

Observe `/profit` result **~2h before** bot stops:

```
ROI: Close trades
∙ -0.00018023 BTC (-9.00%)
∙ -1.363 EUR
ROI: All trades
∙ -0.00018023 BTC (-9.00%)
∙ -1.363 EUR
Total Trade Count: 24
First Trade opened: a day ago
Latest Trade opened: an hour ago
Avg. Duration: 1:52:34
Best Performing: ZEC/BTC: 2.34%
```

Observe `/profit` result  **~3h after** bot is restarted bot stops:

```
ROI: Close trades
∙ -0.00000201 BTC (-0.10%)
∙ -0.015 EUR
ROI: All trades
∙ -0.00000201 BTC (-0.10%)
∙ -0.015 EUR
Total Trade Count: 1
First Trade opened: 41 minutes ago
Latest Trade opened: 41 minutes ago
Avg. Duration: 0:24:17
Best Performing: ETH/BTC: -0.10%
```

Of course, the reset could have happened any time before or after the stopping of the bot, but I did not execute the `\profit` command closer to the event.

Here is the output of the logs from docker; Looks like an API error to me:

```
2018-05-02 06:26:01,428 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/local/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/usr/local/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 389, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 309, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.binance.com', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 349, in fetch
    proxies=self.proxies
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 521, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.binance.com', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/exchange/__init__.py", line 329, in get_markets
    return _API.fetch_markets()
  File "/usr/local/lib/python3.6/site-packages/ccxt/binance.py", line 350, in fetch_markets
    response = self.publicGetExchangeInfo()
  File "/usr/local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 298, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/usr/local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 295, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/usr/local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 359, in fetch
    self.raise_error(RequestTimeout, method, url, e)
  File "/usr/local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 280, in raise_error
    raise exception_type(output)
ccxt.base.errors.RequestTimeout: binance GET https://api.binance.com/api/v1/exchangeInfo HTTPSConnectionPool(host='api.binance.com', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 45, in main
    state = freqtrade.worker(old_state=state)
  File "/freqtrade/freqtrade/freqtradebot.py", line 121, in worker
    nb_assets=nb_assets)
  File "/freqtrade/freqtrade/freqtradebot.py", line 133, in _throttle
    result = func(*args, **kwargs)
  File "/freqtrade/freqtrade/freqtradebot.py", line 153, in _process
    ) if nb_assets else self.config['exchange']['pair_whitelist']
  File "/freqtrade/freqtrade/freqtradebot.py", line 224, in _refresh_whitelist
    markets = exchange.get_markets()
  File "/freqtrade/freqtrade/exchange/__init__.py", line 332, in get_markets
    'Could not load markets due to networking error. Message: {}'.format(e)
freqtrade.NetworkException: Could not load markets due to networking error. Message: binance GET https://api.binance.com/api/v1/exchangeInfo HTTPSConnectionPool(host='api.binance.com', port=443): Read timed out. (read timeout=10)
2018-05-02 06:26:01,431 - freqtrade.rpc.rpc_manager - INFO - *Status:* `Stopping trader...`
2018-05-02 06:26:01,534 - freqtrade.freqtradebot - INFO - Stopping trader and cleaning up modules...
2018-05-02 06:26:01,534 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc.telegram ...
```

**Comment by xmatthias** [comment]
can you please post the exact docker-command you used to 
* run the bot `docker run ...`
* restart the bot (either `docker run ...` or `docker start ...`

i do have the suspicion that you did not mount the Database into the container, so the database only exists within the docker container which was then recreated - resetting trading history.

**Comment by nareshn2003** [comment]
I am facing same problem. My bot was stopped due to same  'Could not load markets due to networking error. Message: {}'.format(e) on binance. Two days ago i have 9 trades open in history .
ID  Pair       Since    Profit
----  ---------  -------  --------
  11  BNB/BTC    21 h     -1.35%
  16  LTC/BTC    18 h     0.58%
  21  XLM/BTC    15 h     -1.58%
  25  STORM/BTC  10 h     -0.76%
  26  NEO/BTC    9 h      -1.15%
  27  ICX/BTC    9 h      -1.93%
  29  TRX/BTC    8 h      -1.29%
  31  STRAT/BTC  4 h      -3.30%
  32  EOS/BTC    3 h      -2.04%

After crash and i restart the bot manually now all previous open trades are gone. I am not using docker , i am using directly on Ubuntu using screen. 

To reproduce this issue run the bot in dry mode and once bot make trades just press Ctrl+C to terminal it will not save any previous order  and upon restart it will be fresh start.

**Comment by gitlines** [comment]
@xmatthias sure:

```
docker run -d \
  --name freqtrade \
  -v /etc/localtime:/etc/localtime:ro \
  -v ~/.freqtrade/config.json:/freqtrade/config.json \
  -v ~/.freqtrade/tradesv3.sqlite:/freqtrade/tradesv3.dryrun.sqlite \
  freqtrade
``
`
I guess that I have mounted the production db to the dryrun db in the container. Moreover, I kept a copy of my `config.json` in the `freqtrade/` directory of the server, which does not seem smart either.

I also realise that I could also use the `--dry-run-db` parameter such as the run command would be like this:

```
docker run -d \
  --name freqtrade \
  -v /etc/localtime:/etc/localtime:ro \
  -v ~/.freqtrade/config.json:/freqtrade/config.json \
  --dry-run-db \
  freqtrade
```
or should the flag be followed by `~/.freqtrade/tradesv3.dryrun.sqlite` ?
Thanks!

**Comment by xmatthias** [comment]
you mount `~/.freqtrade/tradesv3.sqlite` (production naming) to `/freqtrade/tradesv3.dryrun.sqlite` (dry-mode naming).

However - if you don't specify `--dry-run-db`, `/freqtrade/tradesv3.sqlite` will be used within the container - which is not what you mounted.

your 2nd command adds another error (`--dry-run-db` needs to go last) - also, you don't mount it there - so trades will be gone (again).
```
docker run -d \
  --name freqtrade \
  -v /etc/localtime:/etc/localtime:ro \
  -v ~/.freqtrade/config.json:/freqtrade/config.json \
  -v ~/.freqtrade/tradesv3.sqlite:/freqtrade/tradesv3.dryrun.sqlite \
  freqtrade --dry-run-db
```
(assuming the image is called `freqtrade` .
