### ISSUE TITLE
Bot crashes using Okex exchange - ccxt

### ISSUE THREAD

**Issue by sshchmod777** [gcarq/freqtrade#714]
## Step 1: Have you search for this issue before posting it?
Yes
If you have discovered a bug in the bot, please [search our issue tracker](https://github.com/gcarq/freqtrade/issues?q=is%3Aissue). 
If it hasn't been reported, please create a new issue.

## Step 2: Describe your environment

  * Python Version: 3.6
  * Branch: Develop
  * Last Commit ID: 13d6297 
 
## Step 3: Describe the problem:
Bot won't run using Okex exchange.

### Steps to reproduce:

  1. Run the bot using the command (Windows)
```python main.py --strategy BinHV45 backtesting --timerange=20180501- --ticker-interval 1m --realistic-simulation --refresh-pairs-cached```

  
### Observed Results:

  * What happened?
It stops after downloading the data. Won't run the backtesting.
  * What did you expect to happen?
Run the backtest and display results
### Relevant code exceptions or logs:

  ```
2018-05-20 22:30:03,365 - freqtrade.optimize - INFO - Download the pair: "ZIL/BTC", Interval: 1m
dumping json to "freqtrade\tests\testdata\ZIL_BTC-1m.json"
2018-05-20 22:30:04,318 - freqtrade.optimize - INFO - Download the pair: "ZRX/BTC", Interval: 1m
dumping json to "freqtrade\tests\testdata\ZRX_BTC-1m.json"
2018-05-20 22:30:05,321 - freqtrade.optimize - INFO - Download the pair: "TRUE/BTC", Interval: 1m
dumping json to "freqtrade\tests\testdata\TRUE_BTC-1m.json"
Traceback (most recent call last):
  File "D:\bot\okex\freqtrade-develop\.env\lib\site-packages\pandas\core\ops.py", line 1009, in na_op
    result = expressions.evaluate(op, str_rep, x, y, **eval_kwargs)
  File "D:\bot\okex\freqtrade-develop\.env\lib\site-packages\pandas\core\computation\expressions.py", line 205, in evaluate
    return _evaluate(op, op_str, a, b, **eval_kwargs)
  File "D:\bot\okex\freqtrade-develop\.env\lib\site-packages\pandas\core\computation\expressions.py", line 65, in _evaluate_standard
    return op(a, b)
TypeError: unsupported operand type(s) for -: 'str' and 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\bot\okex\freqtrade-develop\.env\lib\site-packages\pandas\core\ops.py", line 1030, in safe_na_op
    return na_op(lvalues, rvalues)
  File "D:\bot\okex\freqtrade-develop\.env\lib\site-packages\pandas\core\ops.py", line 1015, in na_op
    result[mask] = op(x[mask], com._values_from_object(y[mask]))
TypeError: unsupported operand type(s) for -: 'str' and 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 69, in <module>
    main(sys.argv[1:])
  File "main.py", line 31, in main
    args.func(args)
  File "d:\bot\okex\freqtrade-develop\freqtrade\optimize\backtesting.py", line 314, in start
    backtesting.start()
  File "d:\bot\okex\freqtrade-develop\freqtrade\optimize\backtesting.py", line 249, in start
    preprocessed = self.tickerdata_to_dataframe(data)
  File "d:\bot\okex\freqtrade-develop\freqtrade\analyze.py", line 217, in tickerdata_to_dataframe
    for pair, pair_data in tickerdata.items()}
  File "d:\bot\okex\freqtrade-develop\freqtrade\analyze.py", line 217, in <dictcomp>
    for pair, pair_data in tickerdata.items()}
  File "d:\bot\okex\freqtrade-develop\freqtrade\analyze.py", line 75, in populate_indicators
    return self.strategy.populate_indicators(dataframe=dataframe)
  File "d:\bot\okex\freqtrade-develop\freqtrade\strategy\BinHV45.py", line 34, in populate_indicators
    dataframe['pricedelta'] = (dataframe['open'] - dataframe['close']).abs()
  File "D:\bot\okex\freqtrade-develop\.env\lib\site-packages\pandas\core\ops.py", line 1066, in wrapper
    result = safe_na_op(lvalues, rvalues)
  File "D:\bot\okex\freqtrade-develop\.env\lib\site-packages\pandas\core\ops.py", line 1034, in safe_na_op
    lambda x: op(x, rvalues))
  File "pandas\_libs\algos_common_helper.pxi", line 1212, in pandas._libs.algos.arrmap_object
  File "D:\bot\okex\freqtrade-develop\.env\lib\site-packages\pandas\core\ops.py", line 1034, in <lambda>
    lambda x: op(x, rvalues))
TypeError: unsupported operand type(s) for -: 'str' and 'str'
  ```

when i run just the main.py

```Traceback (most recent call last):
  File "d:\bot\okex\freqtrade-develop\freqtrade\analyze.py", line 125, in get_signal
    dataframe = self.analyze_ticker(ticker_hist)
  File "d:\bot\okex\freqtrade-develop\freqtrade\analyze.py", line 107, in analyze_ticker
    dataframe = self.populate_indicators(dataframe)
  File "d:\bot\okex\freqtrade-develop\freqtrade\analyze.py", line 75, in populate_indicators
    return self.strategy.populate_indicators(dataframe=dataframe)
  File "d:\bot\okex\freqtrade-develop\freqtrade\strategy\default_strategy.py", line 44, in populate_indicators
    dataframe['adx'] = ta.ADX(dataframe)
  File "talib/_abstract.pxi", line 352, in talib._ta_lib.Function.__call__
  File "talib/_abstract.pxi", line 383, in talib._ta_lib.Function.__call_function
  File "D:\bot\okex\freqtrade-develop\.env\lib\site-packages\talib\__init__.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "talib/_func.pxi", line 339, in talib._ta_lib.ADX
Exception: high is not double
2018-05-20 22:40:51,935 - freqtrade.analyze - ERROR - Unexpected error when analyzing ticker for pair CHAT/BTC: high is not double
Traceback (most recent call last):
  File "D:\bot\okex\freqtrade-develop\.env\lib\site-packages\talib\__init__.py", line 20, in wrapper
    for arg in chain(args, kwargs.values())
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\bot\okex\freqtrade-develop\freqtrade\analyze.py", line 125, in get_signal
    dataframe = self.analyze_ticker(ticker_hist)
  File "d:\bot\okex\freqtrade-develop\freqtrade\analyze.py", line 107, in analyze_ticker
    dataframe = self.populate_indicators(dataframe)
  File "d:\bot\okex\freqtrade-develop\freqtrade\analyze.py", line 75, in populate_indicators
    return self.strategy.populate_indicators(dataframe=dataframe)
  File "d:\bot\okex\freqtrade-develop\freqtrade\strategy\default_strategy.py", line 44, in populate_indicators
    dataframe['adx'] = ta.ADX(dataframe)
  File "talib/_abstract.pxi", line 352, in talib._ta_lib.Function.__call__
  File "talib/_abstract.pxi", line 383, in talib._ta_lib.Function.__call_function
  File "D:\bot\okex\freqtrade-develop\.env\lib\site-packages\talib\__init__.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "talib/_func.pxi", line 339, in talib._ta_lib.ADX
Exception: high is not double```

**Comment by shusso** [comment]
Thanks for the issue, at the moment, we only support Bittrex and Binance exchanges.
