### ISSUE TITLE
Coinmarketcap timeout causing bot to stop

### ISSUE THREAD

**Issue by nullart** [gcarq/freqtrade#732]
## Step 2: Describe your environment

  * Python Version: 3.6
  * Branch: Develop
  * Last Commit ID: 13d6297b9f52691b0bda1f867222b1c638e0c503
 
## Step 3: Describe the problem:
dry_run enabled, exchange binance

 ### Steps to reproduce: (maybe this is due to coinmarketcap api? )

  1. in mac os (not docker) in dry run, with dynamicwhitelist 30
  2. wait till message will show
  3. get a fatal exception error
  
### Observed Results:

  * Bot stopped
  * Bot should have caught the error and probably throttle

### Relevant code exceptions or logs:

  ```
  // paste your log here
2018-05-21 22:37:13,235 - freqtrade.freqtradebot - INFO - Found no sell signals for whitelisted currencies. Trying again..
2018-05-21 22:37:44,227 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 389, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 309, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.coinmarketcap.com', port=443): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./freqtrade/main.py", line 45, in main
    state = freqtrade.worker(old_state=state)
  File "/freqtrade/freqtrade/freqtrade/freqtradebot.py", line 121, in worker
    nb_assets=nb_assets)
  File "/freqtrade/freqtrade/freqtrade/freqtradebot.py", line 133, in _throttle
    result = func(*args, **kwargs)
  File "/freqtrade/freqtrade/freqtrade/freqtradebot.py", line 165, in _process
    state_changed |= self.process_maybe_execute_sell(trade)
  File "/freqtrade/freqtrade/freqtrade/freqtradebot.py", line 422, in process_maybe_execute_sell
    return self.handle_trade(trade)
  File "/freqtrade/freqtrade/freqtrade/freqtradebot.py", line 486, in handle_trade
    self.execute_sell(trade, current_rate)
  File "/freqtrade/freqtrade/freqtrade/freqtradebot.py", line 607, in execute_sell
    fiat_converter = CryptoToFiatConverter()
  File "/freqtrade/freqtrade/freqtrade/fiat_convert.py", line 90, in __init__
    self._load_cryptomap()
  File "/freqtrade/freqtrade/freqtrade/fiat_convert.py", line 94, in _load_cryptomap
    coinlistings = self._coinmarketcap.listings()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/coinmarketcap/core.py", line 56, in listings
    response = self.__request('listings/', params=None)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/coinmarketcap/core.py", line 34, in __request
    response_object = self.session.get(self.base_url + endpoint, params = params, timeout = self.request_timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests_cache/core.py", line 126, in request
    **kwargs
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests_cache/core.py", line 106, in send
    return send_request_and_cache_response()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests_cache/core.py", line 91, in send_request_and_cache_response
    response = super(CachedSession, self).send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/adapters.py", line 521, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.coinmarketcap.com', port=443): Read timed out. (read timeout=30)
2018-05-21 22:37:44,245 - freqtrade.rpc.rpc_manager - INFO - *Status:* `Stopping trader...`
2018-05-21 22:37:49,253 - freqtrade.rpc.telegram - WARNING - Telegram NetworkError: Timed out! Trying one more time.
2018-05-21 22:37:50,915 - freqtrade.freqtradebot - INFO - Stopping trader and cleaning up modules...
2018-05-21 22:37:50,916 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc.telegram ...
  ```

**Comment by xmatthias** [comment]
Hi,

i just created a PR for this issue. Fiat-convert problems should never cause the bot to stop in my opinion.

**Comment by nullart** [comment]
fixed with PR https://github.com/gcarq/freqtrade/pull/733
