### ISSUE TITLE
Runtime Error , argument error

### ISSUE THREAD

**Issue by ghost** [gcarq/freqtrade#97]
Show the exception message:

2017-11-10 09:39:41,088 - __main__ - INFO - Starting freqtrade 0.14.1
2017-11-10 09:39:41,091 - __main__ - INFO - Validating configuration ...
2017-11-10 09:39:41,112 - JobQueue - DEBUG - JobQueue thread started
2017-11-10 09:39:41,116 - freqtrade.rpc.telegram - INFO - rpc.telegram is listening for following commands: [['status'], ['profit'], ['balance'], ['start'], ['stop'], ['forcesell'], ['performance'], ['count'], ['help'], ['version']]
Traceback (most recent call last):
  File "freqtrade/main.py", line 288, in <module>
    main()
  File "freqtrade/main.py", line 267, in main
    init(_CONF)
  File "freqtrade/main.py", line 226, in init
    exchange.init(config)
  File "/home/tt/freqtrade/freqtrade/exchange/__init__.py", line 52, in init
    _API = exchange_class(exchange_config)
  File "/home/tt/freqtrade/freqtrade/exchange/bittrex.py", line 36, in __init__
    calls_per_second=5,
TypeError: __init__() got an unexpected keyword argument 'calls_per_second'

^CException ignored in: <module 'threading' from '/usr/lib/python3.6/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 1294, in _shutdown
    t.join()
  File "/usr/lib/python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt

**Comment by gcarq** [comment]
We upgraded to python-bittrex 0.2.0, seems like you have an old version of `python-bittrex` installed. Could you please upgrade your dependencies and try it again:
```
$ source .env/bin/activate
$ pip install -r requirements.txt
```
